import { Formation } from '../domain/models/formation.model';

/**
 * Curated Angular training directory (research 2026-07).
 *
 * Honesty rules applied to this data:
 * - `priceVerified: false` on every price the research flagged "à confirmer"
 *   or that fluctuates (promos, subscriptions) — the card shows an "à confirmer"
 *   flag so no misleading figure is presented as fact.
 * - `affiliateUrl` is `null` everywhere: no tracked deep link has been set up
 *   yet. The card falls back to the public `url`, and for the `certificates-dev`
 *   network the referral param is appended by `AffiliateService.buildUrl()`.
 *   `affiliable: true` marks a real/intended partner relationship (disclosed
 *   on the card via the discreet "lien partenaire" flag + rel="sponsored").
 */
export const FORMATIONS: Formation[] = [
  // ── Éditorial picks (Sélection) ──────────────────────────────────────────
  {
    id: 'angular-dev-tutorials',
    title: 'Tutoriels officiels angular.dev',
    author: 'Équipe Angular (Google)',
    lang: 'en',
    pricing: 'free',
    priceLabel: null,
    priceVerified: true,
    level: 'debutant',
    format: 'article',
    url: 'https://angular.dev',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['signals', 'standalone', 'control-flow', 'officiel'],
    blurb: {
      fr: 'Le parcours officiel (signals, standalone, control flow). Toujours à jour, incontournable pour démarrer.',
      en: 'The official learning path (signals, standalone, control flow). Always up to date, the go-to starting point.',
    },
    featured: true,
    featuredPick: 'debutant',
  },
  {
    id: 'ninja-squad-ebook',
    title: 'Become a Ninja with Angular (ebook)',
    author: 'Ninja Squad (Cédric Exbrayat, JB Nizet)',
    lang: 'fr',
    pricing: 'free',
    priceLabel: { fr: 'Prix libre (peut être 0 €)', en: 'Pay what you want (can be €0)' },
    priceVerified: true,
    level: 'intermediaire',
    format: 'article',
    url: 'https://books.ninja-squad.com',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['ebook', 'français', 'référence'],
    blurb: {
      fr: 'LA référence FR, écrite par des contributeurs au framework. Mise à jour à chaque version.',
      en: 'The French reference, written by framework contributors. Updated with every release.',
    },
    featured: true,
    featuredPick: 'fr',
  },
  {
    id: 'pluralsight-angular-signals-kurata',
    title: 'Angular Signals & RxJS (path Angular)',
    author: 'Deborah Kurata · Pluralsight',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Abonnement', en: 'Subscription' },
    priceVerified: false,
    level: 'senior',
    format: 'video',
    url: 'https://www.pluralsight.com/paths/angular-development',
    affiliable: true,
    affiliateNetwork: 'Impact',
    affiliateUrl: null,
    tags: ['signals', 'rxjs', 'reactive', 'senior'],
    blurb: {
      fr: 'Cours Signals (juin 2026) + RxJS par une GDE, dans un parcours structuré. Pour passer senior sur le réactif moderne.',
      en: 'Signals (June 2026) + RxJS courses by a GDE, in a structured path. To reach senior level on modern reactivity.',
    },
    featured: true,
    featuredPick: 'signals',
  },
  {
    id: 'marmicode-pragmatic-testing',
    title: 'Pragmatic Angular Testing Workshop',
    author: 'Younes Jaaidi · Marmicode',
    lang: 'en',
    pricing: 'paid',
    priceLabel: null,
    priceVerified: false,
    level: 'senior',
    format: 'live',
    url: 'https://marmicode.io/workshops/pragmatic-angular-testing',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['testing', 'vitest', 'playwright', 'tdd'],
    blurb: {
      fr: 'La référence testing Angular moderne (Vitest, Playwright, TDD). Pour fiabiliser une codebase en pro.',
      en: 'The modern Angular testing reference (Vitest, Playwright, TDD). To make a codebase reliable, pro-grade.',
    },
    featured: true,
    featuredPick: 'testing',
  },

  // ── EN / international ────────────────────────────────────────────────────
  {
    id: 'udemy-complete-guide-angular',
    title: 'Angular — The Complete Guide',
    author: 'Maximilian Schwarzmüller (Academind)',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: '~15-20 € en promo', en: '~$15-20 on sale' },
    priceVerified: false,
    level: 'debutant',
    format: 'video',
    url: 'https://www.udemy.com/course/the-complete-guide-to-angular-2/',
    affiliable: true,
    affiliateNetwork: 'Impact',
    affiliateUrl: null,
    tags: ['complet', 'signals', 'standalone', 'best-seller'],
    blurb: {
      fr: 'Le best-seller mondial, 36,5 h, re-enregistré en 2024 (signals, standalone). Parcours guidé débutant → avancé.',
      en: 'The world best-seller, 36.5h, re-recorded in 2024 (signals, standalone). Guided beginner-to-advanced path.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'angular-university',
    title: 'Angular University',
    author: 'Vasco Cavalheiro (jhades)',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Abonnement', en: 'Subscription' },
    priceVerified: false,
    level: 'senior',
    format: 'video',
    url: 'https://angular-university.io',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['rxjs', 'ngrx', 'signals', 'testing', 'reactive'],
    blurb: {
      fr: 'Cours réputés RxJS, NgRx, signals et reactive patterns. 200k+ étudiants.',
      en: 'Well-known RxJS, NgRx, signals and reactive-patterns courses. 200k+ students.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'ultimate-courses-angular',
    title: 'Ultimate Angular',
    author: 'Todd Motto · Ultimate Courses',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Bundle par formation', en: 'Per-course bundle' },
    priceVerified: false,
    level: 'intermediaire',
    format: 'video',
    url: 'https://ultimatecourses.com/courses/angular',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['architecture', 'design-patterns', 'perf'],
    blurb: {
      fr: 'Design patterns, architecture, perf. Auteur reconnu, orienté pro.',
      en: 'Design patterns, architecture, performance. Well-known author, pro-oriented.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'frontend-masters-angular',
    title: 'Frontend Masters (Angular & écosystème)',
    author: 'Frontend Masters',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Abonnement', en: 'Subscription' },
    priceVerified: false,
    level: 'intermediaire',
    format: 'video',
    url: 'https://frontendmasters.com',
    affiliable: true,
    affiliateNetwork: 'Direct',
    affiliateUrl: null,
    tags: ['typescript', 'rxjs', 'architecture', 'écosystème'],
    blurb: {
      fr: 'Écosystème front large (TypeScript, RxJS, archi). Cours denses par des experts reconnus.',
      en: 'Broad frontend ecosystem (TypeScript, RxJS, architecture). Dense courses by recognised experts.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'educative-angular',
    title: 'Educative — parcours Angular / front',
    author: 'Educative',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Abonnement', en: 'Subscription' },
    priceVerified: false,
    level: 'debutant',
    format: 'article',
    url: 'https://www.educative.io',
    affiliable: true,
    affiliateNetwork: 'Direct',
    affiliateUrl: null,
    tags: ['interactif', 'text-based', 'front'],
    blurb: {
      fr: 'Apprentissage text-based interactif (pas de vidéo). Parcours front/Angular progressifs.',
      en: 'Interactive text-based learning (no video). Progressive frontend/Angular paths.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'certificates-dev-angular',
    title: 'Certification Angular (+ prep)',
    author: 'Certificates.dev',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Voucher exam', en: 'Exam voucher' },
    priceVerified: false,
    level: 'intermediaire',
    format: 'article',
    url: 'https://certificates.dev/angular',
    affiliable: true,
    affiliateNetwork: 'certificates-dev',
    affiliateUrl: null,
    tags: ['certification', 'junior', 'mid', 'senior'],
    blurb: {
      fr: 'Certif Junior/Mid/Senior + préparation. Le seul parcours certifiant Angular structuré — voir la revue certifs.',
      en: 'Junior/Mid/Senior certification + prep. The only structured Angular certification path — see the certs review.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'deborah-kurata-youtube',
    title: 'Chaîne YouTube Deborah Kurata',
    author: 'Deborah Kurata (GDE)',
    lang: 'en',
    pricing: 'free',
    priceLabel: null,
    priceVerified: true,
    level: 'senior',
    format: 'video',
    url: 'https://youtube.com/@deborah_kurata',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['signals', 'rxjs', 'reactive', 'gratuit'],
    blurb: {
      fr: 'Signals, RxJS et reactive patterns expliqués clairement. Idéal pour monter en niveau sans budget.',
      en: 'Signals, RxJS and reactive patterns, clearly explained. Great for levelling up on no budget.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'joshua-morony-youtube',
    title: 'Chaîne YouTube Joshua Morony',
    author: 'Joshua Morony',
    lang: 'en',
    pricing: 'free',
    priceLabel: null,
    priceVerified: true,
    level: 'intermediaire',
    format: 'video',
    url: 'https://youtube.com/@JoshuaMorony',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['signals', 'architecture', 'reactive', 'gratuit'],
    blurb: {
      fr: 'Angular moderne, signals, architecture réactive. Vidéos courtes et denses.',
      en: 'Modern Angular, signals, reactive architecture. Short, dense videos.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'decoded-frontend',
    title: 'Decoded Frontend',
    author: 'Dmytro Mezhenskyi (GDE)',
    lang: 'en',
    pricing: 'free',
    priceLabel: { fr: 'Gratuit (YouTube) + payant', en: 'Free (YouTube) + paid' },
    priceVerified: true,
    level: 'senior',
    format: 'video',
    url: 'https://youtube.com/@DecodedFrontend',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['change-detection', 'di', 'rxjs', 'avancé'],
    blurb: {
      fr: 'Contenu avancé (change detection, DI, RxJS profond). Pour passer senior.',
      en: 'Advanced content (change detection, DI, deep RxJS). To reach senior level.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'freecodecamp-angular',
    title: 'freeCodeCamp — cours Angular',
    author: 'freeCodeCamp',
    lang: 'en',
    pricing: 'free',
    priceLabel: null,
    priceVerified: true,
    level: 'debutant',
    format: 'video',
    url: 'https://youtube.com/@freecodecamp',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['complet', 'projet', 'gratuit'],
    blurb: {
      fr: 'Cours longs (17 h+), structurés, du zéro au projet.',
      en: 'Long (17h+), structured courses, from zero to a full project.',
    },
    featured: false,
    featuredPick: null,
  },

  // ── Workshops & studios (GDE-led, ex-/ressources créateurs) ───────────────
  {
    id: 'angulararchitects-workshops',
    title: 'Architecture & Micro-Frontends (workshops)',
    author: 'Manfred Steyer · ANGULARarchitects (GDE)',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'À partir de ~1 010 €/workshop', en: 'From ~€1,010/workshop' },
    priceVerified: false,
    level: 'senior',
    format: 'live',
    url: 'https://www.angulararchitects.io/en/angular-workshops/',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['architecture', 'micro-frontends', 'enterprise', 'signals', 'nx'],
    blurb: {
      fr: 'LA référence archi & micro-frontends, en workshops live (public ou intra). Pour les apps à grande échelle.',
      en: 'THE architecture & micro-frontends reference, as live workshops (public or in-house). For large-scale apps.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'angular-experts-workshops',
    title: 'Angular Experts — Workshops (RxJS, NgRx, Mastery)',
    author: 'Tomas Trajan & Kevin Kreuzer (GDE)',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Workshops payants', en: 'Paid workshops' },
    priceVerified: false,
    level: 'senior',
    format: 'live',
    url: 'https://angularexperts.io',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['rxjs', 'ngrx', 'architecture', 'workshop'],
    blurb: {
      fr: 'Workshops live par deux GDE : RxJS réactif, state management NgRx, Angular Mastery. Patterns prêts pour la prod.',
      en: 'Live workshops by two GDEs: reactive RxJS, NgRx state management, Angular Mastery. Production-ready patterns.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'angular-training-chautard',
    title: 'Angular Training — cours on-demand',
    author: 'Alain Chautard (GDE)',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Cours vidéo', en: 'Video courses' },
    priceVerified: false,
    level: 'debutant',
    format: 'video',
    url: 'https://courses.angulartraining.com/',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['fundamentals', 'typescript', 'certification', 'on-demand'],
    blurb: {
      fr: 'Cours vidéo par le GDE derrière la certif Angular (Certificates.dev × Angular Training). Bon socle avant l’examen.',
      en: 'Video courses by the GDE behind the Angular cert (Certificates.dev × Angular Training). A good base before the exam.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'push-based-workshops',
    title: 'Push-Based — Performance Workshops',
    author: 'Michael Hladky',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: 'Workshops payants', en: 'Paid workshops' },
    priceVerified: false,
    level: 'senior',
    format: 'live',
    url: 'https://push-based.io/workshops',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['performance', 'rxangular', 'rxjs', 'architecture'],
    blurb: {
      fr: 'Workshops perf de pointe (RxAngular, rendu, scalabilité). Pour pousser une app Angular à la limite.',
      en: 'Cutting-edge performance workshops (RxAngular, rendering, scalability). To push an Angular app to its limit.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'monsterlessons-academy',
    title: 'Monsterlessons Academy',
    author: 'Oleksandr Kocherhin',
    lang: 'en',
    pricing: 'paid',
    priceLabel: { fr: '~15 $/cours', en: '~$15/course' },
    priceVerified: false,
    level: 'intermediaire',
    format: 'video',
    url: 'https://monsterlessons-academy.com/courses',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['ngrx', 'projet', 'interview', 'pratique'],
    blurb: {
      fr: 'Cours vidéo abordables, orientés pratique : Angular + NgRx sur projet réel, prépa entretien. Bon rapport prix/contenu.',
      en: 'Affordable, hands-on video courses: Angular + NgRx on a real project, interview prep. Great value for money.',
    },
    featured: false,
    featuredPick: null,
  },

  // ── FR / pro ──────────────────────────────────────────────────────────────
  {
    id: 'easyangularkit',
    title: 'EasyAngularKit',
    author: 'Gaëtan Redin',
    lang: 'fr',
    pricing: 'paid',
    priceLabel: { fr: '~184 €/module', en: '~€184/module' },
    priceVerified: false,
    level: 'intermediaire',
    format: 'video',
    url: 'https://www.easyangularkit.com',
    affiliable: true,
    affiliateNetwork: 'Direct',
    affiliateUrl: null,
    tags: ['français', 'pratique', 'projet'],
    blurb: {
      fr: 'Angular FR « par la pratique », solo solide. Le meilleur produit payant 100 % francophone.',
      en: 'Hands-on Angular in French, a solid solo product. The best paid 100% French-language offering.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'ninja-squad-training',
    title: 'Angular : Zero to Ninja',
    author: 'Ninja Squad',
    lang: 'fr',
    pricing: 'paid',
    priceLabel: { fr: '2 400 € / 4 j', en: '€2,400 / 4 days' },
    priceVerified: true,
    level: 'debutant',
    format: 'live',
    url: 'https://ninja-squad.com/trainings/angular',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['français', 'présentiel', 'pro', 'opco'],
    blurb: {
      fr: 'Formation pro FR par des contributeurs au framework. Réputée, inclut le Pro Pack.',
      en: 'Professional French training by framework contributors. Highly regarded, includes the Pro Pack.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'zenika-angular',
    title: 'Formation Angular / Angular Avancé',
    author: 'Zenika',
    lang: 'fr',
    pricing: 'paid',
    priceLabel: { fr: 'Inter/intra', en: 'Inter/intra' },
    priceVerified: false,
    level: 'intermediaire',
    format: 'live',
    url: 'https://training.zenika.com/fr-fr/training/angular/description',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['français', 'opco', 'ngrx', 'ssr'],
    blurb: {
      fr: 'Gros organisme, Angular 20, signals/lazy/RxJS/NgRx. Souvent finançable OPCO.',
      en: 'Large training provider, Angular 20, signals/lazy/RxJS/NgRx. Often OPCO-fundable.',
    },
    featured: false,
    featuredPick: null,
  },
  {
    id: 'dyma-angular',
    title: 'Formation Angular en ligne',
    author: 'Dyma',
    lang: 'fr',
    pricing: 'paid',
    priceLabel: { fr: 'Abonnement plateforme', en: 'Platform subscription' },
    priceVerified: false,
    level: 'debutant',
    format: 'video',
    url: 'https://www.dyma.fr/formations/angular',
    affiliable: false,
    affiliateNetwork: null,
    affiliateUrl: null,
    tags: ['français', 'material', 'ssr', 'abordable'],
    blurb: {
      fr: 'Angular complet FR (Material, SSR), format vidéo à ton rythme, abonnement abordable.',
      en: 'Complete Angular in French (Material, SSR), self-paced video, affordable subscription.',
    },
    featured: false,
    featuredPick: null,
  },
];
