import { CatalogResource } from '../domain/models/catalog-resource.model';

/**
 * Catalog of Angular creators, blogs, channels & newsletters.
 * Source: _archive/redesign/ressources/data.js (verified 2026-06-11). FR copy is the
 * original; EN copy was authored for the bilingual site.
 * Grouped by editorial calibre: Officiel · Références · Pépites solo.
 *
 * NB. Courses & training platforms (Ninja Squad, Udemy, Pluralsight…) do NOT
 * live here — see /carriere/formations.
 */
export const CATALOG_RESOURCES: readonly CatalogResource[] = [
  // ---------- Officiel & fondamentaux ----------
  {
    id: 'angular-dev',
    name: 'angular.dev',
    author: 'Équipe Angular',
    lang: 'en',
    origin: 'EN',
    type: 'doc',
    level: 'tous',
    tier: 'officiel',
    shortDesc: {
      fr: 'La doc officielle refondue : signals, standalone, control flow.',
      en: 'The rebuilt official docs: signals, standalone, control flow.',
    },
    value: {
      fr: 'Le point de vérité. Quand un doute survient, ça se tranche ici.',
      en: 'The source of truth. When in doubt, this settles it.',
    },
    url: 'https://angular.dev',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-blog',
    name: 'Angular Blog',
    author: 'Équipe Angular',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'tous',
    tier: 'officiel',
    shortDesc: {
      fr: 'Annonces de versions, roadmap et deep-dives signés par l’équipe.',
      en: 'Release announcements, roadmap and deep-dives straight from the team.',
    },
    value: {
      fr: 'La source des nouveautés avant tout le monde — directement du framework.',
      en: 'New features before everyone else — straight from the framework.',
    },
    url: 'https://blog.angular.dev',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },

  // ---------- Références incontournables ----------
  {
    id: 'angular-university',
    name: 'Angular University',
    author: 'Vasco Cavalheiro',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'Articles longs et très clairs ; référence pédagogique du domaine.',
      en: 'Long, crystal-clear articles; the field’s teaching reference.',
    },
    value: {
      fr: 'Quand un concept résiste, leur article le rend limpide.',
      en: 'When a concept won’t click, their article makes it obvious.',
    },
    url: 'https://blog.angular-university.io',
    price: 'freemium',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-experts',
    name: 'Angular Experts',
    author: 'GDEs',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'gros',
    shortDesc: {
      fr: 'Angular, NgRx, RxJS, Nx — du contenu actionnable par des GDEs.',
      en: 'Angular, NgRx, RxJS, Nx — actionable content from GDEs.',
    },
    value: {
      fr: 'Des patterns prêts à appliquer en prod, pas de la théorie.',
      en: 'Production-ready patterns, not theory.',
    },
    url: 'https://angularexperts.io/blog',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-architects',
    name: 'ANGULARarchitects',
    author: 'Manfred Steyer',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'gros',
    shortDesc: {
      fr: 'LA référence architecture & micro-frontends, par un GDE.',
      en: 'THE reference on architecture & micro-frontends, by a GDE.',
    },
    value: {
      fr: 'Indispensable dès que ton app grossit et que la structure compte.',
      en: 'Essential once your app grows and structure starts to matter.',
    },
    url: 'https://angulararchitects.io/blog',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-training',
    name: 'Angular Training — Daily',
    author: 'Alain Chautard (GDE)',
    lang: 'en',
    origin: 'EN',
    type: 'newsletter',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'Un tip Angular par jour, format ultra-digeste.',
      en: 'One Angular tip a day, in an ultra-digestible format.',
    },
    value: {
      fr: 'La veille passive idéale : 30 s par jour, tu restes à jour sans effort.',
      en: 'Ideal passive watch: 30s a day keeps you up to date effortlessly.',
    },
    url: 'https://www.angulartraining.com/daily-newsletter',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'fireship',
    name: 'Fireship',
    author: 'Jeff Delaney',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'Web dev moderne en formats courts et percutants.',
      en: 'Modern web dev in short, punchy formats.',
    },
    value: {
      fr: 'Parfait pour saisir une techno en 100 secondes avant d’y plonger.',
      en: 'Perfect to grasp a tech in 100 seconds before diving in.',
    },
    url: 'https://www.youtube.com/@Fireship',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'traversy',
    name: 'Traversy Media',
    author: 'Brad Traversy',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'debutant',
    tier: 'gros',
    shortDesc: {
      fr: 'Tutos complets et très pédagogues pour démarrer.',
      en: 'Complete, beginner-friendly tutorials to get started.',
    },
    value: {
      fr: 'Le grand classique pour construire un premier vrai projet de A à Z.',
      en: 'The classic for building a first real project end to end.',
    },
    url: 'https://www.youtube.com/@TraversyMedia',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'mosh',
    name: 'Programming with Mosh',
    author: 'Mosh Hamedani',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'debutant',
    tier: 'gros',
    shortDesc: {
      fr: '2M+ abonnés, des explications limpides pour bien commencer.',
      en: '2M+ subscribers, crystal-clear explanations to start right.',
    },
    value: {
      fr: 'La pédagogie posée qui rassure quand tout est encore flou.',
      en: 'Calm teaching that reassures when everything still feels fuzzy.',
    },
    url: 'https://www.youtube.com/@programmingwithmosh',
    price: 'freemium',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'freecodecamp',
    name: 'freeCodeCamp',
    author: 'Communauté',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'debutant',
    tier: 'gros',
    shortDesc: {
      fr: 'Des cours Angular longs (17 h+) entièrement gratuits.',
      en: 'Long Angular courses (17h+), entirely free.',
    },
    value: {
      fr: 'Une formation complète sans débourser un centime — imbattable.',
      en: 'A complete course without spending a cent — unbeatable.',
    },
    url: 'https://www.youtube.com/@freecodecamp',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },

  // ---------- Pépites & créateurs solo ----------
  {
    id: 'decoded-frontend',
    name: 'Decoded Frontend',
    author: 'Dmytro Mezhenskyi',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'avance',
    tier: 'solo',
    shortDesc: {
      fr: 'GDE + MVP : DI, Renderer2, signals — du contenu avancé.',
      en: 'GDE + MVP: DI, Renderer2, signals — advanced content.',
    },
    value: {
      fr: 'Pour passer un cap technique : il va là où les tutos s’arrêtent.',
      en: 'To level up technically: he goes where tutorials stop.',
    },
    url: 'https://www.youtube.com/DecodedFrontend',
    price: 'freemium',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'netbasal',
    name: 'Netanel Basal',
    author: 'Netanel Basal',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'solo',
    shortDesc: {
      fr: 'Tech Lead, fondateur @ngneat ; décortique les features méconnues.',
      en: 'Tech Lead, @ngneat founder; dissects little-known features.',
    },
    value: {
      fr: 'Les astuces qu’on ne trouve pas dans la doc, expliquées simplement.',
      en: 'The tricks you won’t find in the docs, explained simply.',
    },
    url: 'https://netbasal.com',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'devtobecurious',
    name: 'Dev to be curious',
    author: 'Evan',
    lang: 'fr',
    origin: 'FR',
    type: 'blog',
    level: 'intermediaire',
    tier: 'solo',
    shortDesc: {
      fr: 'Standalone, signals, .NET, IA — apprendre autrement, en français.',
      en: 'Standalone, signals, .NET, AI — learning differently, in French.',
    },
    value: {
      fr: 'Une voix FR curieuse qui relie Angular et l’écosystème large.',
      en: 'A curious French voice connecting Angular to the wider ecosystem.',
    },
    url: 'https://devtobecurious.fr',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'justa',
    name: 'Benoît Eveillard — justa',
    author: 'Benoît Eveillard',
    lang: 'fr',
    origin: 'FR',
    type: 'blog',
    level: 'intermediaire',
    tier: 'solo',
    shortDesc: {
      fr: 'Sites « AI-ready », RAG, angle GEO/AEO — front + IA, en français.',
      en: '“AI-ready” sites, RAG, GEO/AEO angle — front + AI, in French.',
    },
    value: {
      fr: 'Pertinent pour anticiper le tournant IA du métier front.',
      en: 'Relevant for anticipating the AI shift in frontend work.',
    },
    url: 'https://justa.dev',
    price: 'gratuit',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
];
