import { CatalogResource } from '../domain/models/catalog-resource.model';

/**
 * Catalog of Angular creators, blogs, channels & newsletters.
 * Source: _archive/redesign/ressources/data.js (verified 2026-06-11). FR copy is the
 * original; EN copy was authored for the bilingual site.
 * Grouped by editorial calibre: Officiel · Références · Pépites solo.
 *
 * NB. Courses & training platforms (Ninja Squad, Udemy, Pluralsight…) do NOT
 * live here — see /carriere/formations.
 */
export const CATALOG_RESOURCES: readonly CatalogResource[] = [
  // ---------- Officiel & fondamentaux ----------
  {
    id: 'angular-dev',
    name: 'angular.dev',
    author: 'Équipe Angular',
    lang: 'en',
    origin: 'EN',
    type: 'doc',
    level: 'tous',
    tier: 'officiel',
    shortDesc: {
      fr: 'La doc officielle refondue : signals, standalone, control flow.',
      en: 'The rebuilt official docs: signals, standalone, control flow.',
    },
    value: {
      fr: 'Le point de vérité. Quand un doute survient, ça se tranche ici.',
      en: 'The source of truth. When in doubt, this settles it.',
    },
    url: 'https://angular.dev',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-blog',
    name: 'Angular Blog',
    author: 'Équipe Angular',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'tous',
    tier: 'officiel',
    shortDesc: {
      fr: 'Annonces de versions, roadmap et deep-dives signés par l’équipe.',
      en: 'Release announcements, roadmap and deep-dives straight from the team.',
    },
    value: {
      fr: 'La source des nouveautés avant tout le monde — directement du framework.',
      en: 'New features before everyone else — straight from the framework.',
    },
    url: 'https://blog.angular.dev',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },

  // ---------- Références incontournables ----------
  {
    id: 'angular-university',
    name: 'Angular University',
    author: 'Vasco Cavalheiro',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'Articles longs et très clairs ; référence pédagogique du domaine.',
      en: 'Long, crystal-clear articles; the field’s teaching reference.',
    },
    value: {
      fr: 'Quand un concept résiste, leur article le rend limpide.',
      en: 'When a concept won’t click, their article makes it obvious.',
    },
    url: 'https://blog.angular-university.io',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-experts',
    name: 'Angular Experts',
    author: 'GDEs',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'gros',
    shortDesc: {
      fr: 'Angular, NgRx, RxJS, Nx — du contenu actionnable par des GDEs.',
      en: 'Angular, NgRx, RxJS, Nx — actionable content from GDEs.',
    },
    value: {
      fr: 'Des patterns prêts à appliquer en prod, pas de la théorie.',
      en: 'Production-ready patterns, not theory.',
    },
    url: 'https://angularexperts.io/blog',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-architects',
    name: 'ANGULARarchitects',
    author: 'Manfred Steyer',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'gros',
    shortDesc: {
      fr: 'LA référence architecture & micro-frontends, par un GDE.',
      en: 'THE reference on architecture & micro-frontends, by a GDE.',
    },
    value: {
      fr: 'Indispensable dès que ton app grossit et que la structure compte.',
      en: 'Essential once your app grows and structure starts to matter.',
    },
    url: 'https://angulararchitects.io/blog',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-training',
    name: 'Angular Training — Daily',
    author: 'Alain Chautard (GDE)',
    lang: 'en',
    origin: 'EN',
    type: 'newsletter',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'Un tip Angular par jour, format ultra-digeste.',
      en: 'One Angular tip a day, in an ultra-digestible format.',
    },
    value: {
      fr: 'La veille passive idéale : 30 s par jour, tu restes à jour sans effort.',
      en: 'Ideal passive watch: 30s a day keeps you up to date effortlessly.',
    },
    url: 'https://www.angulartraining.com/daily-newsletter',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'fireship',
    name: 'Fireship',
    author: 'Jeff Delaney',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'Web dev moderne en formats courts et percutants.',
      en: 'Modern web dev in short, punchy formats.',
    },
    value: {
      fr: 'Parfait pour saisir une techno en 100 secondes avant d’y plonger.',
      en: 'Perfect to grasp a tech in 100 seconds before diving in.',
    },
    url: 'https://www.youtube.com/@Fireship',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'traversy',
    name: 'Traversy Media',
    author: 'Brad Traversy',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'debutant',
    tier: 'gros',
    shortDesc: {
      fr: 'Tutos complets et très pédagogues pour démarrer.',
      en: 'Complete, beginner-friendly tutorials to get started.',
    },
    value: {
      fr: 'Le grand classique pour construire un premier vrai projet de A à Z.',
      en: 'The classic for building a first real project end to end.',
    },
    url: 'https://www.youtube.com/@TraversyMedia',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'mosh',
    name: 'Programming with Mosh',
    author: 'Mosh Hamedani',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'debutant',
    tier: 'gros',
    shortDesc: {
      fr: '2M+ abonnés, des explications limpides pour bien commencer.',
      en: '2M+ subscribers, crystal-clear explanations to start right.',
    },
    value: {
      fr: 'La pédagogie posée qui rassure quand tout est encore flou.',
      en: 'Calm teaching that reassures when everything still feels fuzzy.',
    },
    url: 'https://www.youtube.com/@programmingwithmosh',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'freecodecamp',
    name: 'freeCodeCamp',
    author: 'Communauté',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'debutant',
    tier: 'gros',
    shortDesc: {
      fr: 'Des cours Angular longs (17 h+) entièrement gratuits.',
      en: 'Long Angular courses (17h+), entirely free.',
    },
    value: {
      fr: 'Une formation complète sans débourser un centime — imbattable.',
      en: 'A complete course without spending a cent — unbeatable.',
    },
    url: 'https://www.youtube.com/@freecodecamp',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'monsterlessons',
    name: 'Monsterlessons Academy',
    author: 'Oleksandr Kocherhin',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'intermediaire',
    tier: 'gros',
    shortDesc: {
      fr: 'Tutos Angular/NgRx sur projets réels, publication très régulière.',
      en: 'Angular/NgRx tutorials on real projects, published very regularly.',
    },
    value: {
      fr: 'Pour voir des patterns appliqués de bout en bout, pas juste des snippets.',
      en: 'To see patterns applied end to end, not just snippets.',
    },
    url: 'https://www.youtube.com/@MonsterlessonsAcademy',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-space',
    name: 'Angular Space',
    author: 'Daniel Glejzner',
    lang: 'en',
    origin: 'EN',
    type: 'community',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'Communauté + articles + épisodes « Angular from the Inside ».',
      en: 'Community + articles + “Angular from the Inside” episodes.',
    },
    value: {
      fr: 'Un hub vivant pour rester connecté à l’écosystème Angular.',
      en: 'A living hub to stay plugged into the Angular ecosystem.',
    },
    url: 'https://www.angularspace.com/',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'ng-news',
    name: 'ng-news',
    author: 'ng-news (communauté)',
    lang: 'en',
    origin: 'INTL',
    type: 'newsletter',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'La newsletter hebdo curée de la communauté Angular (aussi ES/PT).',
      en: 'The weekly curated newsletter of the Angular community (also ES/PT).',
    },
    value: {
      fr: 'Une veille triée : que l’essentiel, avec analyse, chaque semaine.',
      en: 'Filtered watch: only what matters, with analysis, every week.',
    },
    url: 'https://medium.com/ng-news',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'angular-plus-show',
    name: 'The Angular Plus Show',
    author: 'ng-conf',
    lang: 'en',
    origin: 'EN',
    type: 'podcast',
    level: 'tous',
    tier: 'gros',
    shortDesc: {
      fr: 'Podcast officiel ng-conf : roadmap, invités de l’équipe Angular.',
      en: 'Official ng-conf podcast: roadmap, guests from the Angular team.',
    },
    value: {
      fr: 'La veille en audio, avec les gens qui font le framework.',
      en: 'Audio watch, with the people who actually build the framework.',
    },
    url: 'https://open.spotify.com/show/1PrLErQHBqBhZsRV1KHhGM',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },

  // ---------- Pépites & créateurs solo ----------
  {
    id: 'decoded-frontend',
    name: 'Decoded Frontend',
    author: 'Dmytro Mezhenskyi',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'avance',
    tier: 'solo',
    shortDesc: {
      fr: 'GDE + MVP : DI, Renderer2, signals — du contenu avancé.',
      en: 'GDE + MVP: DI, Renderer2, signals — advanced content.',
    },
    value: {
      fr: 'Pour passer un cap technique : il va là où les tutos s’arrêtent.',
      en: 'To level up technically: he goes where tutorials stop.',
    },
    url: 'https://www.youtube.com/DecodedFrontend',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'netbasal',
    name: 'Netanel Basal',
    author: 'Netanel Basal',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'solo',
    shortDesc: {
      fr: 'Tech Lead, fondateur @ngneat ; décortique les features méconnues.',
      en: 'Tech Lead, @ngneat founder; dissects little-known features.',
    },
    value: {
      fr: 'Les astuces qu’on ne trouve pas dans la doc, expliquées simplement.',
      en: 'The tricks you won’t find in the docs, explained simply.',
    },
    url: 'https://netbasal.com',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'devtobecurious',
    name: 'Dev to be curious',
    author: 'Evan',
    lang: 'fr',
    origin: 'FR',
    type: 'blog',
    level: 'intermediaire',
    tier: 'solo',
    shortDesc: {
      fr: 'Standalone, signals, .NET, IA — apprendre autrement, en français.',
      en: 'Standalone, signals, .NET, AI — learning differently, in French.',
    },
    value: {
      fr: 'Une voix FR curieuse qui relie Angular et l’écosystème large.',
      en: 'A curious French voice connecting Angular to the wider ecosystem.',
    },
    url: 'https://devtobecurious.fr',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'justa',
    name: 'Benoît Eveillard — justa',
    author: 'Benoît Eveillard',
    lang: 'fr',
    origin: 'FR',
    type: 'blog',
    level: 'intermediaire',
    tier: 'solo',
    shortDesc: {
      fr: 'Sites « AI-ready », RAG, angle GEO/AEO — front + IA, en français.',
      en: '“AI-ready” sites, RAG, GEO/AEO angle — front + AI, in French.',
    },
    value: {
      fr: 'Pertinent pour anticiper le tournant IA du métier front.',
      en: 'Relevant for anticipating the AI shift in frontend work.',
    },
    url: 'https://justa.dev',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'marmicode',
    name: 'Marmicode — Younes Jaaidi',
    author: 'Younes Jaaidi',
    lang: 'fr',
    origin: 'FR',
    type: 'youtube',
    level: 'avance',
    tier: 'solo',
    shortDesc: {
      fr: 'GDE FR : testing Angular pragmatique (zoneless, Vitest, Playwright CT).',
      en: 'French GDE: pragmatic Angular testing (zoneless, Vitest, Playwright CT).',
    },
    value: {
      fr: 'La référence francophone du test Angular — rare et précieux.',
      en: 'The go-to French voice on Angular testing — rare and precious.',
    },
    url: 'https://www.youtube.com/marmicode',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'joshua-morony',
    name: 'Joshua Morony',
    author: 'Joshua Morony',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'intermediaire',
    tier: 'solo',
    shortDesc: {
      fr: '100 % Angular moderne : signals, RxJS+signals, code déclaratif.',
      en: 'All-in on modern Angular: signals, RxJS+signals, declarative code.',
    },
    value: {
      fr: 'Pour penser Angular « signals-first » sans retomber dans les vieux réflexes.',
      en: 'To think Angular “signals-first” without falling back on old habits.',
    },
    url: 'https://www.youtube.com/@JoshuaMorony',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'deborah-kurata',
    name: 'Deborah Kurata',
    author: 'Deborah Kurata',
    lang: 'en',
    origin: 'EN',
    type: 'youtube',
    level: 'intermediaire',
    tier: 'solo',
    shortDesc: {
      fr: 'GDE/MVP : RxJS + Signals expliqués « better together ».',
      en: 'GDE/MVP: RxJS + Signals explained “better together”.',
    },
    value: {
      fr: 'La pédagogie qui fait enfin cliquer la réactivité moderne.',
      en: 'The teaching that finally makes modern reactivity click.',
    },
    url: 'https://www.youtube.com/@deborah_kurata',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'push-based',
    name: 'push-based.io — Enea Jahollari',
    author: 'Enea Jahollari',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'solo',
    shortDesc: {
      fr: 'GDE : performance & signals de pointe (FormValueControl, OnPush par défaut).',
      en: 'GDE: cutting-edge performance & signals (FormValueControl, default OnPush).',
    },
    value: {
      fr: 'Pour comprendre où va Angular avant tout le monde, côté perf.',
      en: 'To see where Angular is heading on performance before everyone else.',
    },
    url: 'https://push-based.io/',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'tim-deschryver',
    name: 'Tim Deschryver',
    author: 'Tim Deschryver',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'solo',
    shortDesc: {
      fr: 'MVP : 200+ articles Angular, testing, NgRx, Signal Forms.',
      en: 'MVP: 200+ posts on Angular, testing, NgRx, Signal Forms.',
    },
    value: {
      fr: 'Un fonds d’articles énorme et à jour, surtout sur le testing.',
      en: 'A huge, up-to-date archive of posts, especially on testing.',
    },
    url: 'https://timdeschryver.dev/blog',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
  {
    id: 'mgechev',
    name: 'Minko Gechev',
    author: 'Minko Gechev',
    lang: 'en',
    origin: 'EN',
    type: 'blog',
    level: 'avance',
    tier: 'solo',
    shortDesc: {
      fr: 'Product lead Angular chez Google : vision framework & roadmap.',
      en: 'Angular product lead at Google: framework vision & roadmap.',
    },
    value: {
      fr: 'La direction du framework expliquée par celui qui la pilote.',
      en: 'The framework’s direction, straight from the person steering it.',
    },
    url: 'https://blog.mgechev.com/',
    cpf: 'na',
    affiliable: false,
    affiliateNetwork: null,
  },
];
