import { Platform } from '../domain/models/platform.model';

/**
 * Curated directory of channels to find dev work (research 2026-07).
 *
 * Honesty rules applied to this data:
 * - Commissions, management fees and referral bonuses fluctuate with profile,
 *   volume and negotiation. Every `feePct` / `flatFeeEur` is an *approximation*
 *   (the card prefixes it with "~") and must be re-checked on the channel's own
 *   site before relying on it.
 * - `affiliable: true` marks a real/intended partner relationship (referral or
 *   affiliate program), disclosed on the card + rel="sponsored nofollow".
 *   `affiliateUrl` is `null` everywhere: no tracked deep link is set up yet, so
 *   the card falls back to the public `url`. Payout amounts are deliberately NOT
 *   displayed — they vary too much to present as fact.
 * - `remoteFriendly` is honest: most consultancies are `hybride`, not full remote.
 */
export const PLATFORMS: Platform[] = [
  // ── 1. Missions freelance — France / francophone ─────────────────────────
  {
    id: 'malt',
    name: 'Malt',
    category: 'freelance',
    geo: 'fr',
    model: 'commission',
    feePct: 10,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.malt.fr',
    affiliable: true,
    affiliateType: 'apport-affaires',
    affiliateUrl: null,
    blurb: {
      fr: 'Le leader européen du freelancing. Commission dégressive ~10 %→5 %, et seulement 2 % sur les clients que tu amènes.',
      en: 'Europe’s leading freelancing platform. Degressive ~10%→5% commission, and just 2% on clients you bring yourself.',
    },
    featured: true,
    pepite: false,
    tags: ['généraliste', 'pme', 'grands-comptes', 'europe'],
  },
  {
    id: 'comet',
    name: 'Comet',
    category: 'freelance',
    geo: 'fr',
    model: 'commission',
    feePct: 5,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.comet.co',
    affiliable: true,
    affiliateType: 'parrainage',
    affiliateUrl: 'https://www.comet.co/fr/freelances/parrainage',
    blurb: {
      fr: 'Missions IT filtrées et envoyées, souvent chez des grands comptes. Curation en amont, ~5 % côté freelance.',
      en: 'Filtered IT gigs pushed to you, often at large companies. Upfront curation, ~5% on the freelancer side.',
    },
    featured: true,
    pepite: false,
    tags: ['it', 'grands-comptes', 'curation'],
  },
  {
    id: 'lehibou',
    name: 'LeHibou',
    category: 'freelance',
    geo: 'fr',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.lehibou.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'IT/tech avec des missions longues (6-18 mois) chez des grands comptes et ETI. Gratuit côté freelance, le client paie la marge.',
      en: 'IT/tech with long missions (6-18 months) at large companies and mid-caps. Free for freelancers, the client pays the margin.',
    },
    featured: false,
    pepite: false,
    tags: ['it', 'missions-longues', 'grands-comptes'],
  },
  {
    id: '404works',
    name: '404Works',
    category: 'freelance',
    geo: 'fr',
    model: 'gratuit',
    feePct: 0,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.404works.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Plateforme tech/web historique (2009) à 0 % de commission. Inscription gratuite, premium optionnel.',
      en: 'Long-running tech/web platform (2009) with 0% commission. Free sign-up, optional premium tier.',
    },
    featured: false,
    pepite: false,
    tags: ['web', 'tech', '0-commission'],
  },
  {
    id: 'collective',
    name: 'Collective',
    category: 'freelance',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.collective.work',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Pensée pour les collectifs de freelances tech/produit : mise en relation et outillage pour travailler à plusieurs.',
      en: 'Built for collectives of tech/product freelancers: matching plus tooling to work as a team.',
    },
    featured: false,
    pepite: false,
    tags: ['collectif', 'produit', 'tech'],
  },
  {
    id: 'creme-de-la-creme',
    name: 'Crème de la Crème',
    category: 'freelance',
    geo: 'fr',
    model: 'commission',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.cremedelacreme.io',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Marketplace digitale au positionnement « élite », candidature filtrée. Sélectif, orienté profils seniors.',
      en: 'Digital marketplace with an “elite” positioning and a filtered application. Selective, senior-oriented.',
    },
    featured: false,
    pepite: false,
    tags: ['digital', 'sélectif', 'senior'],
  },

  // ── 1b. Missions freelance — international / remote ───────────────────────
  {
    id: 'braintrust',
    name: 'Braintrust',
    category: 'freelance',
    geo: 'intl',
    model: 'commission',
    feePct: 0,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://www.usebraintrust.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: '0 % côté freelance (tu gardes 100 % de ton tarif). Réseau coopératif, grands comptes, 100 % remote.',
      en: '0% on the freelancer side (you keep 100% of your rate). Co-op network, large accounts, fully remote.',
    },
    featured: true,
    pepite: false,
    tags: ['remote', 'coop', 'grands-comptes', '0-commission'],
  },
  {
    id: 'lemon-io',
    name: 'Lemon.io',
    category: 'freelance',
    geo: 'intl',
    model: 'commission',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://lemon.io',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Matching rapide dev ↔ startups, EU-friendly, pas de frais upfront. Très sélectif (~1 % d’acceptation).',
      en: 'Fast dev ↔ startup matching, EU-friendly, no upfront fees. Very selective (~1% acceptance).',
    },
    featured: false,
    pepite: false,
    tags: ['remote', 'startups', 'matching', 'europe'],
  },
  {
    id: 'toptal',
    name: 'Toptal',
    category: 'freelance',
    geo: 'intl',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://www.toptal.com',
    affiliable: true,
    affiliateType: 'parrainage',
    affiliateUrl: null,
    blurb: {
      fr: 'Réseau « top 3 % » senior, grands comptes, tarifs élevés. Screening réputé dur — prestige mais entrée difficile.',
      en: 'A senior “top 3%” network, large accounts, high rates. Famously hard screening — prestige, but tough to get in.',
    },
    featured: false,
    pepite: false,
    tags: ['remote', 'senior', 'grands-comptes', 'sélectif'],
  },
  {
    id: 'upwork',
    name: 'Upwork',
    category: 'freelance',
    geo: 'intl',
    model: 'commission',
    feePct: 10,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://www.upwork.com',
    affiliable: true,
    affiliateType: 'affiliation',
    affiliateUrl: null,
    blurb: {
      fr: 'Marketplace généraliste mondiale, tous budgets, peu filtrée. Gros volume mais concurrence par les prix.',
      en: 'A global generalist marketplace, all budgets, lightly filtered. High volume but heavy price competition.',
    },
    featured: false,
    pepite: false,
    tags: ['remote', 'généraliste', 'volume'],
  },
  {
    id: 'wellfound',
    name: 'Wellfound',
    category: 'freelance',
    geo: 'intl',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://wellfound.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Ex-AngelList Talent : startups tech, CDI et contrat, gratuit côté talent. Volume surtout US (fuseau à checker).',
      en: 'Formerly AngelList Talent: tech startups, permanent + contract, free for talent. Mostly US volume (check the time zone).',
    },
    featured: false,
    pepite: false,
    tags: ['remote', 'startups', 'us'],
  },

  // ── 2. CDI / job boards — France ─────────────────────────────────────────
  {
    id: 'welovedevs',
    name: 'WeLoveDevs',
    category: 'cdi',
    geo: 'fr',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://welovedevs.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Job board spécialisé devs : ciblage Angular fin, CDI + freelance, gratuit côté candidat. Le meilleur signal FR pur dev.',
      en: 'A dev-specialised job board: sharp Angular targeting, permanent + freelance, free for candidates. The best pure-dev FR signal.',
    },
    featured: true,
    pepite: false,
    tags: ['dev', 'angular', 'cdi'],
  },
  {
    id: 'welcome-to-the-jungle',
    name: 'Welcome to the Jungle',
    category: 'cdi',
    geo: 'fr',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.welcometothejungle.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Job board + marque employeur : fiches boîtes riches (photos, vidéos, culture), bons filtres remote. Idéal pour cibler.',
      en: 'Job board + employer branding: rich company profiles (photos, videos, culture) and good remote filters. Great for targeting.',
    },
    featured: true,
    pepite: false,
    tags: ['marque-employeur', 'culture', 'cdi'],
  },
  {
    id: 'free-work',
    name: 'Free-Work',
    category: 'cdi',
    geo: 'fr',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.free-work.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Board IT/tech FR fort en TJM : CDI + freelance, ESN visibles. Bon pour front et fullstack, gratuit côté candidat.',
      en: 'A French IT/tech board strong on day rates: permanent + freelance, consultancies visible. Good for front and fullstack, free.',
    },
    featured: false,
    pepite: false,
    tags: ['it', 'tjm', 'cdi', 'freelance'],
  },
  {
    id: 'hellowork',
    name: 'HelloWork',
    category: 'cdi',
    geo: 'fr',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.hellowork.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Généraliste à gros volume (600+ offres « Angular »). Beaucoup de choix mais signal bruité (ESN, présentiel).',
      en: 'High-volume generalist (600+ “Angular” listings). Lots of choice but a noisy signal (consultancies, on-site).',
    },
    featured: false,
    pepite: false,
    tags: ['généraliste', 'volume'],
  },
  {
    id: 'apec',
    name: 'APEC',
    category: 'cdi',
    geo: 'fr',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.apec.fr',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Le board des cadres FR (CDI), données fiables et accompagnement. Utile, mais peu « produit remote ».',
      en: 'The French board for salaried professionals (permanent), reliable data and support. Useful, but light on remote-product roles.',
    },
    featured: false,
    pepite: false,
    tags: ['cadres', 'cdi', 'france'],
  },

  // ── 2b. CDI / job boards — remote-first (intl / EU) ──────────────────────
  {
    id: 'eu-remote-jobs',
    name: 'EU Remote Jobs',
    category: 'cdi',
    geo: 'intl',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://euremotejobs.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Offres remote sur fuseaux européens uniquement : la contrainte de fuseau est réglée. Le plus pertinent pour un profil FR.',
      en: 'Remote roles on European time zones only: the time-zone constraint is solved. The most relevant board for a French profile.',
    },
    featured: true,
    pepite: false,
    tags: ['remote', 'europe', 'fuseau-eu'],
  },
  {
    id: 'remotive',
    name: 'Remotive',
    category: 'cdi',
    geo: 'intl',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://remotive.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Remote curé + communauté, avec un filtre Europe dédié. Bonne qualité de tri pour du remote sérieux.',
      en: 'Curated remote + community, with a dedicated Europe filter. Well-triaged listings for serious remote work.',
    },
    featured: false,
    pepite: false,
    tags: ['remote', 'europe', 'communauté'],
  },
  {
    id: 'remoteok',
    name: 'RemoteOK',
    category: 'cdi',
    geo: 'intl',
    model: 'gratuit',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://remoteok.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Gros volume remote mondial, salaires souvent affichés, filtres angular/typescript. Fort biais US (fuseau à vérifier).',
      en: 'High-volume global remote, salaries often shown, angular/typescript filters. Strong US bias (check the time zone).',
    },
    featured: false,
    pepite: false,
    tags: ['remote', 'volume', 'us'],
  },

  // ── 3. ESN — pépites (taille humaine, réputation craft) ──────────────────
  {
    id: 'zenika',
    name: 'Zenika',
    category: 'esn',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'hybride',
    url: 'https://www.zenika.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'ESN craft de référence : formation, communauté, sponsor de confs — et Angular-friendly. Remote plutôt hybride.',
      en: 'A benchmark craft consultancy: training, community, conference sponsor — and Angular-friendly. Remote is mostly hybrid.',
    },
    featured: true,
    pepite: true,
    tags: ['craft', 'formation', 'angular', 'communauté'],
  },
  {
    id: 'ippon',
    name: 'Ippon Technologies',
    category: 'esn',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'hybride',
    url: 'https://fr.ippon.tech',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Craft cloud/DevOps solide, bonne réputation dev. Angular pertinent. Télétravail flexible mais hybride.',
      en: 'Solid cloud/DevOps craft with a good dev reputation. Angular-relevant. Flexible but hybrid remote.',
    },
    featured: false,
    pepite: true,
    tags: ['craft', 'cloud', 'devops', 'angular'],
  },
  {
    id: 'shodo',
    name: 'Shodo',
    category: 'esn',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://shodo.io',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'ESN « militante » : craft, transparence salariale et redistribution. Historiquement très pro-remote.',
      en: 'An “activist” consultancy: craft, salary transparency and profit-sharing. Historically very pro-remote.',
    },
    featured: false,
    pepite: true,
    tags: ['craft', 'transparence', 'remote'],
  },
  {
    id: 'sipios',
    name: 'Sipios',
    category: 'esn',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'oui',
    url: 'https://www.sipios.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Petite équipe craft fintech (groupe Theodo). Télétravail autorisé pour les devs. Stack plutôt React côté produit.',
      en: 'A small fintech craft team (Theodo group). Remote allowed for devs. Product stack leans React.',
    },
    featured: false,
    pepite: true,
    tags: ['craft', 'fintech', 'react'],
  },
  {
    id: 'octo-technology',
    name: 'Octo Technology',
    category: 'esn',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'hybride',
    url: 'https://www.octo.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Craft reconnu (héritage OCTO), conseil tech exigeant, désormais dans le groupe Accenture. Remote hybride.',
      en: 'Well-known craft (OCTO heritage), demanding tech consulting, now part of Accenture. Hybrid remote.',
    },
    featured: false,
    pepite: true,
    tags: ['craft', 'conseil', 'architecture'],
  },
  {
    id: 'sfeir',
    name: 'Sfeir',
    category: 'esn',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'hybride',
    url: 'https://www.sfeir.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Communauté tech active (GDG, meetups), bonne réputation dev et Angular-friendly. Remote hybride.',
      en: 'An active tech community (GDG, meetups), good dev reputation and Angular-friendly. Hybrid remote.',
    },
    featured: false,
    pepite: true,
    tags: ['craft', 'communauté', 'angular', 'gdg'],
  },

  // ── 3b. ESN — grosses (volume, notoriété) ────────────────────────────────
  {
    id: 'capgemini',
    name: 'Capgemini',
    category: 'esn',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'hybride',
    url: 'https://www.capgemini.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Le mastodonte : énorme volume de projets et de clients. Réputation dev variable selon la mission. Remote hybride.',
      en: 'The giant: a huge volume of projects and clients. Dev reputation varies by assignment. Hybrid remote.',
    },
    featured: false,
    pepite: false,
    tags: ['grand-groupe', 'volume'],
  },
  {
    id: 'onepoint',
    name: 'Onepoint',
    category: 'esn',
    geo: 'fr',
    model: 'na',
    feePct: null,
    flatFeeEur: null,
    remoteFriendly: 'hybride',
    url: 'https://www.groupeonepoint.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Conseil + tech, avis internes plutôt bons pour sa taille. Bon compromis entre gros groupe et culture. Remote hybride.',
      en: 'Consulting + tech, with fairly good internal reviews for its size. A middle ground between big-group and culture. Hybrid remote.',
    },
    featured: false,
    pepite: false,
    tags: ['conseil', 'tech'],
  },

  // ── 4. Portage salarial (cadre & statut) ─────────────────────────────────
  {
    id: 'jump',
    name: 'Jump',
    category: 'portage',
    geo: 'fr',
    model: 'forfait',
    feePct: null,
    flatFeeEur: 99,
    remoteFriendly: 'na',
    url: 'https://www.join-jump.com',
    affiliable: true,
    affiliateType: 'parrainage',
    affiliateUrl: null,
    blurb: {
      fr: 'Portage next-gen, 100 % digital, au forfait fixe (~99 €/mois). Très rentable à CA élevé, où le % classique coûterait plus.',
      en: 'A next-gen, fully digital umbrella at a flat fee (~€99/mo). Very cost-effective at high revenue, where a classic % would cost more.',
    },
    featured: true,
    pepite: false,
    tags: ['digital', 'forfait', 'ca-élevé'],
  },
  {
    id: 'itg',
    name: 'ITG',
    category: 'portage',
    geo: 'fr',
    model: 'frais-gestion',
    feePct: 8,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.itg.fr',
    affiliable: true,
    affiliateType: 'parrainage',
    affiliateUrl: null,
    blurb: {
      fr: 'Le portage historique (1996) : frais ~6-10 % dégressifs, accompagnement et ateliers recherche de mission. Crédibilité max.',
      en: 'The historic umbrella (1996): degressive ~6-10% fees, coaching and mission-hunting workshops. Maximum credibility.',
    },
    featured: false,
    pepite: false,
    tags: ['historique', 'accompagnement'],
  },
  {
    id: 'regie-portage',
    name: 'Régie Portage',
    category: 'portage',
    geo: 'fr',
    model: 'frais-gestion',
    feePct: 5,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.regieportage.fr',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Frais à ~5 % plafonnés (autour de 650 €/mois) : très intéressant à CA élevé, comme un forfait déguisé.',
      en: 'Fees around ~5% but capped (roughly €650/mo): very attractive at high revenue, like a disguised flat fee.',
    },
    featured: false,
    pepite: false,
    tags: ['frais-capés', 'ca-élevé'],
  },
  {
    id: 'embarq',
    name: 'Embarq',
    category: 'portage',
    geo: 'fr',
    model: 'frais-gestion',
    feePct: 6,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.embarq.fr',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Frais ~6 % plafonnés (autour de 600 €/mois), gestion des impayés, accompagnement sur-mesure. Bon compromis.',
      en: 'Fees around ~6% capped (roughly €600/mo), unpaid-invoice handling, tailored support. A good middle ground.',
    },
    featured: false,
    pepite: false,
    tags: ['frais-capés', 'sur-mesure'],
  },
  {
    id: 'webportage',
    name: 'Webportage',
    category: 'portage',
    geo: 'fr',
    model: 'frais-gestion',
    feePct: 7,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.webportage.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Digital-first, spécialisé IT/web (une majorité de consultants tech). Frais ~5-9 %. Parle le même langage que toi.',
      en: 'Digital-first, specialised in IT/web (a majority of tech consultants). Fees ~5-9%. Speaks your language.',
    },
    featured: false,
    pepite: false,
    tags: ['digital', 'it', 'web'],
  },
  {
    id: 'cadres-en-mission',
    name: 'Cadres en Mission',
    category: 'portage',
    geo: 'fr',
    model: 'frais-gestion',
    feePct: 7,
    flatFeeEur: null,
    remoteFriendly: 'na',
    url: 'https://www.cadresenmission.com',
    affiliable: false,
    affiliateType: null,
    affiliateUrl: null,
    blurb: {
      fr: 'Portage orienté cadres et consultants, frais dégressifs (jusqu’à ~7 %). Réseau établi, généraliste.',
      en: 'An umbrella aimed at professionals and consultants, degressive fees (up to ~7%). An established, generalist network.',
    },
    featured: false,
    pepite: false,
    tags: ['cadres', 'consultants'],
  },
];
