// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY.
// Run `npm run generate:jobs` (or `npm run build`) to regenerate.
import type { Job } from '../domain/models/job.model';

export const JOBS_DATA: readonly Job[] = [
  {
    "slug": "viabill-senior-frontend-angular-remote-eu",
    "title": "Senior Frontend Developer (Angular)",
    "company": "ViaBill",
    "companyLogo": "",
    "type": "Freelance",
    "remote": "100",
    "zone": "EU",
    "location": "Europe — 100 % remote, résidents UE uniquement",
    "language": "en",
    "salary": "Non communiqué (contrat B2B)",
    "tjm": null,
    "stack": [
      "Angular",
      "NgRx",
      "TypeScript",
      "Jest",
      "Node.js"
    ],
    "url": "https://jobs.lever.co/viabill/db393d02-e09b-4abc-a3d2-94e411e74618",
    "scannedAt": "2026-10-02",
    "status": "active",
    "tags": [
      "angular",
      "remote-eu",
      "salaire-non-communique",
      "fintech",
      "ngrx"
    ],
    "editorialHook": "Du Angular 20 + NgRx pur, 100 % remote ouvert à toute l'UE, chez un pionnier du BNPL. Seule ombre : pas de salaire affiché.",
    "editorialNote": "ViaBill est un pionnier danois du paiement fractionné (plus de 150 M$ de\ntransactions par an), avec une équipe entièrement distribuée. Le poste est du\nAngular moderne sans compromis : Angular 20+, NgRx complet, TypeScript strict,\nJest, plus des microservices Node.js/Express à posséder. L'annonce écrit\n« Fully remote - EU residents only ». Deux réserves : la fourchette n'est pas\naffichée (c'est l'exception assumée de ce board, étiquetée\n« salaire non communiqué »), et le formulaire demande des prétentions « in euros\non B2B contract » : pour un·e résident·e français·e, c'est du freelance. Le test\ntechnique évalue aussi un journal écrit de tes échanges avec l'IA.\n",
    "editorialHookEn": "Pure Angular 20 + NgRx, fully remote across the EU, at a BNPL pioneer. The one catch: no posted salary.",
    "editorialNoteEn": "ViaBill is a Danish buy-now-pay-later pioneer (over $150M in transactions a\nyear) with a fully distributed team. This is modern Angular with no compromise:\nAngular 20+, full NgRx, strict TypeScript, Jest, plus Node.js/Express\nmicroservices to own. The posting says « Fully remote - EU residents only ». Two\ncaveats: no posted range (the one deliberate exception on this board, tagged\n« salary not disclosed »), and the application form asks for expectations « in\neuros on B2B contract », so this is contractor work. The take-home test also\ngrades a written log of your AI interactions.\n",
    "locationEn": "Europe — fully remote, EU residents only",
    "salaryEn": "Not disclosed (B2B contract)"
  },
  {
    "slug": "builderio-senior-customer-engineer-emea",
    "title": "Senior Customer Engineer (EMEA)",
    "company": "Builder.io",
    "companyLogo": "",
    "type": "CDI",
    "remote": "100",
    "zone": "EU",
    "location": "Remote — zone EMEA",
    "language": "en",
    "salary": "120 000 – 160 000 € (fixe + variable) + equity",
    "tjm": null,
    "stack": [
      "JavaScript",
      "TypeScript",
      "Angular",
      "React",
      "Vue",
      "GraphQL",
      "LLM"
    ],
    "url": "https://job-boards.greenhouse.io/builder/jobs/5359270004",
    "scannedAt": "2026-10-02",
    "status": "expired",
    "tags": [
      "remote-emea",
      "salaire-affiche",
      "angular",
      "ia",
      "customer-engineering"
    ],
    "editorialHook": "120-160 k€ affichés, remote EMEA, et Angular cité parmi les frameworks attendus. Un poste client, pas du front pur.",
    "editorialNote": "Builder.io est une plateforme de développement assistée par IA (Fusion,\nPublish) utilisée par J.Crew, Schneider Electric et Anheuser-Busch. Le poste\nn'est pas du front-end pur : on accompagne les grands comptes sur leurs\nintégrations, on anime des ateliers, on écrit de la doc et des exemples de code,\net on remonte le terrain à la roadmap. Mais le prérequis n°1 est bien\nl'ingénierie front : « 6+ years of experience with HTML, CSS, JavaScript, and\nmodern front-end frameworks such as React, Vue, Angular, or similar ». La\nfourchette est écrite dans l'annonce : 120 000 – 160 000 € fixe + variable, plus\nequity. À côté : congés illimités (3 semaines minimum), 12 semaines de congé\nparental à taux plein, fenêtre d'exercice des stock-options de 10 ans.\n",
    "editorialHookEn": "€120-160k posted, remote EMEA, and Angular named among the expected frameworks. A customer-facing role, not pure front-end.",
    "editorialNoteEn": "Builder.io is an AI development platform (Fusion, Publish) used by J.Crew,\nSchneider Electric and Anheuser-Busch. This isn't pure front-end: you guide\nenterprise customers through integrations, run workshops, write docs and code\nsamples, and feed what you learn back into the roadmap. But requirement number\none is front-end engineering: « 6+ years of experience with HTML, CSS,\nJavaScript, and modern front-end frameworks such as React, Vue, Angular, or\nsimilar ». The range is in the posting: €120,000 – €160,000 base plus target\nvariable, plus equity. Alongside: unlimited time off (3 weeks minimum), 12\nweeks of fully paid parental leave, a 10-year option exercise window.\n",
    "locationEn": "Remote — EMEA region",
    "salaryEn": "€120,000 – €160,000 (base + target variable) + equity"
  },
  {
    "slug": "serpapi-developer-advocate-french",
    "title": "Developer Advocate (francophone)",
    "company": "SerpApi",
    "companyLogo": "",
    "type": "Freelance",
    "remote": "100",
    "zone": "Worldwide",
    "location": "Remote-first — ouvert au monde entier",
    "language": "en",
    "salary": "100 000 – 125 000 $/an (contrat indépendant)",
    "tjm": null,
    "stack": [
      "JavaScript",
      "API",
      "Documentation",
      "DevRel"
    ],
    "url": "https://serpapi.com/careers/french-developer-advocate",
    "scannedAt": "2026-10-02",
    "status": "active",
    "tags": [
      "devrel",
      "remote-worldwide",
      "salaire-affiche",
      "francophone"
    ],
    "editorialHook": "Un poste de Developer Advocate dédié au marché francophone, ouvert depuis n'importe où, avec la fourchette affichée.",
    "editorialNote": "SerpApi publie ses comptes, sa roadmap et ses salaires, ce qui reste rarissime\nen DevRel européen. Verbatim : « No matter where you're based, you can be part\nof our diverse, remote-first team. » À savoir avant de postuler : hors d'Austin\n(TX), l'entreprise recrute en independent contractor, pas en salarié. C'est donc\ndu freelance, bien payé et à horaires libres. Le poste demande de localiser la\ndoc, de créer du contenu technique en français, d'animer les communautés dev\nfrancophones et de parler en meetup : le profil d'un dev qui écrit, pas d'un\nmarketeur.\n",
    "editorialHookEn": "A Developer Advocate role dedicated to the French-speaking market, open from anywhere, with the range in plain sight.",
    "editorialNoteEn": "SerpApi publishes its books, its roadmap and its pay, which is still rare in\nEuropean DevRel. Straight from the posting: « No matter where you're based, you\ncan be part of our diverse, remote-first team. » Worth knowing: outside Austin,\nTX, the company hires independent contractors, not employees, so this is\nfreelance work, well paid and on your own schedule. The role covers localising\ndocs, writing technical content in French, engaging French-speaking dev\ncommunities and speaking at meetups: a developer who writes, not a marketer.\n",
    "locationEn": "Remote-first — open worldwide",
    "salaryEn": "$100,000 – $125,000/year (independent contractor)"
  },
  {
    "slug": "serpapi-javascript-developer-advocate",
    "title": "Developer Advocate JavaScript",
    "company": "SerpApi",
    "companyLogo": "",
    "type": "Freelance",
    "remote": "100",
    "zone": "Worldwide",
    "location": "Remote-first — ouvert au monde entier",
    "language": "en",
    "salary": "100 000 – 125 000 $/an + intéressement (contrat indépendant)",
    "tjm": null,
    "stack": [
      "JavaScript",
      "TypeScript",
      "SDK",
      "API",
      "DevRel"
    ],
    "url": "https://serpapi.com/careers/javascript-developer-advocate",
    "scannedAt": "2026-10-02",
    "status": "active",
    "tags": [
      "devrel",
      "remote-worldwide",
      "salaire-affiche",
      "javascript",
      "sdk"
    ],
    "editorialHook": "Maintenir un SDK JavaScript, écrire, parler en conf, avec une fourchette affichée : ça n'arrive presque jamais en DevRel.",
    "editorialNote": "Le poste est concret : maintenir le SDK JS, construire des projets d'exemple,\naméliorer la doc, intervenir en meetup et en conférence. Aucun framework imposé :\n« Solid experience with Javascript is required ». Clients cités : Nvidia,\nShopify, Perplexity, Adobe, Samsung. Hors d'Austin (TX), le recrutement se fait\nen independent contractor. En contrepartie : fonctionnement 100 % asynchrone,\nhoraires libres, environnement explicitement neurodivergent-friendly.\nL'intéressement aux bénéfices s'ajoute à la fourchette de base.\n",
    "editorialHookEn": "Maintain a JavaScript SDK, write, speak at conferences, with a posted range: that almost never happens in DevRel.",
    "editorialNoteEn": "The work is concrete: maintain the JS SDK, build example projects, improve the\ndocs, speak at meetups and conferences. No framework is imposed: « Solid\nexperience with Javascript is required ». Customers named: Nvidia, Shopify,\nPerplexity, Adobe, Samsung. Outside Austin, TX, hiring is as an independent\ncontractor. In exchange: fully async, flexible hours, an explicitly\nneurodivergent-friendly environment. Profit share sits on top of the base range.\n",
    "locationEn": "Remote-first — open worldwide",
    "salaryEn": "$100,000 – $125,000/year + profit share (independent contractor)"
  },
  {
    "slug": "dougs-senior-software-engineer-portail-facturation",
    "title": "Senior Software Engineer — Squad Portail Facturation",
    "company": "Dougs",
    "companyLogo": "",
    "type": "CDI",
    "remote": "100",
    "zone": "FR",
    "location": "France — 100 % à distance (bureaux à Bron, près de Lyon)",
    "language": "fr",
    "salary": "50 000 – 55 000 €/an",
    "tjm": null,
    "stack": [
      "Angular",
      "NestJS",
      "TypeScript",
      "PostgreSQL",
      "Jest",
      "GCP"
    ],
    "url": "https://careers.dougs.fr/jobs/8454141-senior-software-engineer-squad-portail-facturation-h-f",
    "scannedAt": "2026-10-02",
    "status": "active",
    "tags": [
      "angular",
      "remote-france",
      "salaire-affiche",
      "nestjs",
      "fintech"
    ],
    "editorialHook": "CDI français, 100 % télétravail, salaire écrit dans l'annonce et Angular en première ligne, chez un client final qui recrute toute son équipe à distance.",
    "editorialNote": "Dougs est un cabinet d'expertise comptable nouvelle génération (450 personnes\ndont plus de 90 ingénieurs, 42 000 entrepreneurs clients) qui développe son\napplication en interne : un client final, pas une ESN. Le statut est écrit sur\nla fiche : « Entièrement à distance », avec « Dans nos locaux, en télétravail\npartiel ou à 100 %, tout est possible » et un rassemblement par trimestre à\nBron. Le poste est fullstack avec une vraie moitié front (« Angular côté front,\nNestJS/PostgreSQL côté back ») et la squad compte une experte front. Le sujet :\nla réforme de la facturation électronique, donc du produit sous contrainte\nréglementaire. Prérequis : 5 ans de fullstack, NestJS/TypeScript solide,\nPostgreSQL, à l'aise en Angular, tests non négociables, DDD apprécié.\nRémunération affichée : 50 000 à 55 000 € par an. Process : deux visios, un test\ntechnique à la maison, un débrief avec l'équipe. Annonce republiée le 25/09/2026.\n",
    "editorialHookEn": "A French permanent contract, fully remote, salary in the ad and Angular up front, at a product company that hires its whole team remotely.",
    "editorialNoteEn": "Dougs is a new-generation French accounting firm (450 people including 90+\nengineers, 42,000 business clients) that builds its own app in-house: a product\ncompany, not a consultancy. The listing says « Entièrement à distance » (fully\nremote), with office, partial or full remote all possible and one team\ngathering per quarter in Bron. The role is full-stack with a genuine front-end\nhalf (Angular on the front, NestJS/PostgreSQL on the back) and the squad\nincludes a dedicated front-end expert. The subject: France's e-invoicing\nreform, so regulated product work. Requirements: 5 years full-stack, solid\nNestJS/TypeScript, PostgreSQL, comfortable in Angular, tests non-negotiable,\nDDD welcome. Posted pay: €50,000 – €55,000 per year. Process: two video calls,\na take-home test, a debrief with the team. The role is in French.\n",
    "locationEn": "France — fully remote (offices in Bron, near Lyon)",
    "salaryEn": "€50,000 – €55,000/year"
  },
  {
    "slug": "n2jsoft-developpeur-fullstack-confirme-dotnet-angular",
    "title": "Développeur fullstack confirmé H/F (C#, .Net, Angular)",
    "company": "N2JSoft (N2F)",
    "companyLogo": "",
    "type": "CDI",
    "remote": "100",
    "zone": "FR",
    "location": "France — full remote, une semaine sur site par trimestre (Montagnat, Ain)",
    "language": "fr",
    "salary": "40 000 – 50 000 €/an",
    "tjm": null,
    "stack": [
      "Angular",
      "TypeScript",
      ".NET",
      "C#",
      "PostgreSQL",
      "AWS"
    ],
    "url": "https://n2jsoft.recruitee.com/o/developpeur-fullstack-confirme-hf-c-net-angular-12",
    "scannedAt": "2026-10-02",
    "status": "active",
    "tags": [
      "angular",
      "remote-france",
      "salaire-affiche",
      "dotnet",
      "saas-b2b"
    ],
    "editorialHook": "Éditeur SaaS rentable, full remote avec une semaine par trimestre sur site, 40-50 k€ affichés et une migration Angular 16 → 21 en cours.",
    "editorialNote": "N2JSoft édite N2F, un logiciel de notes de frais et de factures fournisseurs\n(20 000 clients, 1 million d'utilisateurs, 220 personnes dont 45 en tech) :\nun client final rentable, pas une ESN. Le poste est fullstack avec une vraie\nmoitié front : « Front : Angular 16/21 », .NET 10 et C# côté back, MSSQL,\nPostgreSQL et DynamoDB, sur AWS, en monolithe modulaire. Prérequis : 3 ans de\n.NET/C# et 2 ans d'Angular, donc un niveau confirmé plutôt que senior.\nLe télétravail est écrit noir sur blanc : full remote possible, avec une semaine\nde présence par trimestre prise en charge par l'entreprise. À savoir : si tu\nhabites à moins d'une heure de Montagnat (Ain), l'entreprise attend plutôt un ou\ndeux jours sur site par semaine. Rémunération affichée : 40 000 à 50 000 € brut\npar an. Process : test technique à la maison (7 jours), revue de code d'une heure,\nentretien avec le CTO.\n",
    "editorialHookEn": "Profitable SaaS vendor, fully remote with one week on site per quarter, €40-50k posted and an Angular 16 → 21 migration under way.",
    "editorialNoteEn": "N2JSoft builds N2F, an expense-report and supplier-invoice tool (20,000\ncustomers, 1 million users, 220 people including 45 in tech): a profitable\nproduct company, not a consultancy. The role is full-stack with a genuine\nfront-end half: « Front : Angular 16/21 », .NET 10 and C# on the back end,\nMSSQL, PostgreSQL and DynamoDB, on AWS, in a modular monolith. Requirements:\n3 years of .NET/C# and 2 years of Angular, so mid-level rather than senior.\nRemote is in writing: fully remote is possible, with one company-paid week on\nsite per quarter. Worth knowing: if you live within an hour of Montagnat (Ain,\nnear Lyon), the company expects one or two days a week on site. Posted pay:\n€40,000 – €50,000 gross per year. Process: a take-home test (7 days), a\none-hour code review, an interview with the CTO. The role is in French.\n",
    "locationEn": "France — fully remote, one week on site per quarter (Montagnat, Ain)",
    "salaryEn": "€40,000 – €50,000/year"
  },
  {
    "slug": "agicap-senior-software-engineer-nodejs-angular",
    "title": "Senior Software Engineer (NodeJS / Angular)",
    "company": "Agicap",
    "companyLogo": "",
    "type": "CDI",
    "remote": "100",
    "zone": "FR",
    "location": "France — full remote ou hybride Lyon/Paris",
    "language": "fr",
    "salary": "60 000 – 70 000 €/an",
    "tjm": null,
    "stack": [
      "Angular",
      "TypeScript",
      "Node.js",
      "NestJS",
      "PostgreSQL",
      "SQL Server",
      "GCP"
    ],
    "url": "https://jobs.lever.co/agicap/17e34e47-fed3-44a3-9019-4b1af309f48c",
    "scannedAt": "2026-10-02",
    "status": "expired",
    "tags": [
      "angular",
      "remote-france",
      "salaire-affiche",
      "nestjs",
      "fintech",
      "saas-b2b"
    ],
    "editorialHook": "Éditeur SaaS lyonnais, full remote écrit noir sur blanc, 60-70 k€ affichés et Angular 20 : la fourchette la plus haute de ce board pour un CDI français 100 % remote.",
    "editorialNote": "Agicap édite un logiciel de gestion de trésorerie pour entreprises de taille\nintermédiaire (8 000 clients, 600 personnes, 145 M€ levés, siège à Lyon Vaise) :\nun client final, pas une ESN. L'annonce écrit « Full remote ou Hybride\n(Lyon/Paris), venues à Lyon non obligatoires ». Stack : TypeScript,\nNode.js/NestJS, Angular 20, SQL Server et PostgreSQL, sur GCP, avec mise en\nproduction quotidienne. L'équipe utilise des assistants de code (dont Claude\nCode) au quotidien. Fourchette affichée : 60 000 – 70 000 € par an.\nLa réserve, dite franchement : le profil met en avant une « forte expérience\nback-end (souvent ~7 ans+) » et NestJS est prioritaire. Angular est une vraie\npartie du poste, pas son centre de gravité. Process : un entretien de\nmotivation, un pair programming de 2 h, une revue de code de 2 h.\n",
    "editorialHookEn": "Lyon-based SaaS vendor, full remote in writing, €60-70k posted and Angular 20: the highest band on this board for a 100% remote French permanent role.",
    "editorialNoteEn": "Agicap builds cash-management software for mid-sized companies (8,000\ncustomers, 600 people, €145M raised, HQ in Lyon Vaise): a product company, not\na consultancy. The posting says « Full remote ou Hybride (Lyon/Paris), venues à\nLyon non obligatoires » (full remote or hybrid, trips to Lyon optional).\nStack: TypeScript, Node.js/NestJS, Angular 20, SQL Server and PostgreSQL, on\nGCP, with daily production releases. The team uses coding assistants\n(including Claude Code) every day. Posted range: €60,000 – €70,000 per year.\nThe caveat, said plainly: the profile stresses strong back-end experience\n(often ~7 years+) and NestJS comes first. Angular is a real part of the role,\nnot its centre of gravity. Process: a motivation interview, a 2-hour pair\nprogramming session, a 2-hour code review. The role and interviews are in French.\n",
    "locationEn": "France — full remote or hybrid Lyon/Paris",
    "salaryEn": "€60,000 – €70,000/year"
  },
  {
    "slug": "hospitable-senior-frontend-angular",
    "title": "Senior Front-End Angular Product Engineer",
    "company": "Hospitable",
    "companyLogo": "",
    "type": "CDI",
    "remote": "100",
    "zone": "EU",
    "location": "Europe (remote-only)",
    "language": "fr",
    "salary": "134 450 - 167 258 USD/an + equity ($HOST RSUs) + PSUs jusqu'à 387k$/an",
    "tjm": null,
    "stack": [
      "Angular",
      "RxJS",
      "Tailwind",
      "Ionic (bonus)"
    ],
    "url": "https://apply.workable.com/hospitable/j/3C7DDE165E/",
    "scannedAt": "2026-06-01",
    "status": "expired",
    "tags": [
      "angular",
      "remote-eu",
      "salaire-affiche",
      "product-engineer",
      "saas"
    ],
    "editorialHook": "Du vrai Angular moderne, 100% remote Europe, et une fourchette de salaire affichée à 6 chiffres en dollars — rare combinaison.",
    "editorialNote": "Hospitable est un SaaS remote-only (logiciel d'automatisation pour locations\nAirbnb/Vrbo) qui cherche un Senior Front-End sur du Angular moderne + RxJS\n+ Tailwind, avec bonus Ionic/web components. La fourchette est affichée\nnoir sur blanc (134 450-167 258 USD), plus equity et PSUs — niveau de\ntransparence salariale qu'on voit surtout chez les boîtes US, ici ouverte\nà l'Europe. 35 jours de congés, culture async-first. C'est exactement le\ntype de poste qu'un dev Angular senior FR peut viser sans bouger de chez lui.\n",
    "editorialHookEn": "Real modern Angular, 100% remote across Europe, and a six-figure USD salary range stated up front — a rare combination.",
    "editorialNoteEn": "Hospitable is a remote-only SaaS (automation software for Airbnb/Vrbo\nrentals) hiring a Senior Front-End engineer on modern Angular + RxJS +\nTailwind, with bonus points for Ionic/web components. The range is\npublished in black and white (134,450-167,258 USD), plus equity and PSUs\n— a level of pay transparency usually seen only at US companies, here\nopen to Europe. 35 days off, async-first culture. Exactly the kind of role\na senior FR Angular dev can target without leaving home.\n",
    "salaryEn": "134,450 - 167,258 USD/year + equity ($HOST RSUs) + PSUs up to $387k/year"
  },
  {
    "slug": "aircall-frontend-remote-france",
    "title": "Frontend Engineer (Remote France)",
    "company": "Aircall",
    "companyLogo": "",
    "type": "CDI",
    "remote": "100",
    "zone": "FR",
    "location": "France",
    "language": "fr",
    "salary": "65k-90k€",
    "tjm": null,
    "stack": [
      "Angular",
      "TypeScript",
      "GraphQL"
    ],
    "url": "https://aircall.welcometothejungle.com/",
    "scannedAt": "2026-05-16",
    "status": "expired",
    "tags": [
      "angular",
      "remote-france",
      "cdi-senior"
    ],
    "editorialHook": "100% frontend, pas mixé back. Médiane FR plutôt 65-90k.",
    "editorialNote": "Aircall continue de recruter en remote France. Position 100% frontend\n(pas fullstack imposé), TJM-équivalent intéressant pour qui veut sortir\ndes plateformes ESN classiques. À vérifier la stack exacte côté Angular\nvs autre framework lors du screening initial avec la RH.\n"
  }
] as const;
