// AUTO-GENERATED from _archive/redesign/carriere/entretien-data.js (one-time conversion).
// 69 bilingual Angular interview questions, 8 macro-themes.
import type { InterviewQuestion, InterviewTheme } from '../domain/models/interview-question.model';

export const INTERVIEW_THEMES: readonly InterviewTheme[] = [
  {
    id: 'fondamentaux',
    label: {
      fr: 'Fondamentaux JS/TS',
      en: 'JS/TS fundamentals',
    },
  },
  {
    id: 'angular-core',
    label: {
      fr: 'Angular Core',
      en: 'Angular Core',
    },
  },
  {
    id: 'rxjs-signals',
    label: {
      fr: 'RxJS & Signals',
      en: 'RxJS & Signals',
    },
  },
  {
    id: 'architecture',
    label: {
      fr: 'Architecture & État',
      en: 'Architecture & State',
    },
  },
  {
    id: 'performance',
    label: {
      fr: 'Performance',
      en: 'Performance',
    },
  },
  {
    id: 'testing',
    label: {
      fr: 'Tests & Tooling',
      en: 'Testing & Tooling',
    },
  },
  {
    id: 'a11y',
    label: {
      fr: 'Accessibilité',
      en: 'Accessibility',
    },
  },
  {
    id: 'soft',
    label: {
      fr: 'Soft skills & Lead',
      en: 'Soft skills & Lead',
    },
  },
] as const;

export const INTERVIEW_QUESTIONS: readonly InterviewQuestion[] = [
  {
    id: '1.1',
    theme: 'fondamentaux',
    fine: 'Fondamentaux JS/TS & Web',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce que JavaScript ?",
      en: 'What is JavaScript?',
    },
    a: {
      fr: "Langage **interprété**, **dynamiquement typé**, **multi-paradigme** (impératif, OO, fonctionnel), **single-threaded** (asynchrone via l'event loop) et **basé sur les prototypes**.",
      en: 'An **interpreted**, **dynamically typed**, **multi-paradigm** (imperative, OO, functional), **single-threaded** language (async via the event loop) that is **prototype-based**.',
    },
  },
  {
    id: '1.2',
    theme: 'fondamentaux',
    fine: 'Fondamentaux JS/TS & Web',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: 'JavaScript est-il orienté objet ?',
      en: 'Is JavaScript object-oriented?',
    },
    a: {
      fr: "Pas au sens **classique** (Java/C#). C'est un langage **à prototypes** : héritage par prototype, propriétés ajoutables à la volée. Les `class` ES6 ne sont que du sucre syntaxique au-dessus des prototypes.",
      en: "Not in the **classical** sense (Java/C#). It's **prototype-based**: inheritance via prototype, properties added on the fly. ES6 `class` is just syntactic sugar over prototypes.",
    },
  },
  {
    id: '1.3',
    theme: 'fondamentaux',
    fine: 'Fondamentaux JS/TS & Web',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'une classe ?",
      en: 'What is a class?',
    },
    a: {
      fr: "Un **modèle** (blueprint) qui définit la structure (propriétés) et le comportement (méthodes) d'objets, avec un `constructor` appelé à la création.",
      en: 'A **blueprint** defining the structure (properties) and behavior (methods) of objects, with a `constructor` called on creation.',
    },
  },
  {
    id: '1.4',
    theme: 'fondamentaux',
    fine: 'Fondamentaux JS/TS & Web',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'une instance ?",
      en: 'What is an instance?',
    },
    a: {
      fr: "Un **objet concret** créé à partir d'une classe via `new`. Analogie : classe = moule, instance = gâteau.",
      en: 'A **concrete object** created from a class via `new`. Analogy: class = mold, instance = cake.',
    },
  },
  {
    id: '1.5',
    theme: 'fondamentaux',
    fine: 'Fondamentaux JS/TS & Web',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'une implémentation de classe ?",
      en: 'What is a class implementation?',
    },
    a: {
      fr: "Le **code concret** qui réalise un contrat défini par une `interface`. L'interface dit **quoi** (signatures), l'implémentation dit **comment** (`class X implements Y`).",
      en: 'The **concrete code** fulfilling a contract defined by an `interface`. The interface says **what** (signatures), the implementation says **how** (`class X implements Y`).',
    },
  },
  {
    id: '1.6',
    theme: 'fondamentaux',
    fine: 'Fondamentaux JS/TS & Web',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce que le DOM ?",
      en: 'What is the DOM?',
    },
    a: {
      fr: 'Une **représentation en arbre** de la page HTML, exposée comme API pour lire/modifier contenu, structure et style. En Angular on évite la manipulation directe : on passe par le binding et la change detection.',
      en: 'A **tree representation** of the HTML page, exposed as an API to read/modify content, structure and style. In Angular we avoid direct manipulation and rely on binding and change detection.',
    },
  },
  {
    id: '1.7',
    theme: 'fondamentaux',
    fine: 'Fondamentaux JS/TS & Web',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'une API ?",
      en: 'What is an API?',
    },
    a: {
      fr: 'Une **interface de programmation** = un **contrat** qui spécifie comment des logiciels échangent des données. Types : REST (HTTP), GraphQL, WebSocket (temps réel), SOAP (XML, ancien).',
      en: 'A **programming interface** = a **contract** specifying how software exchanges data. Types: REST (HTTP), GraphQL, WebSocket (real-time), SOAP (XML, legacy).',
    },
  },
  {
    id: '2.1',
    theme: 'angular-core',
    fine: 'Components & Architecture',
    diff: 1,
    modern: true,
    seed: false,
    q: {
      fr: 'Définis un component Angular.',
      en: 'Define an Angular component.',
    },
    a: {
      fr: "Une **classe TS** décorée `@Component` qui contrôle une portion de l'UI : un décorateur (métadonnées), un template (HTML) et de la logique (classe). 💡 **2026** : **standalone par défaut** (plus de `NgModule`), **OnPush** recommandé, `input()`/`output()` en fonctions signal.",
      en: 'A **TS class** decorated with `@Component` that controls a slice of the UI: decorator (metadata), template (HTML), logic (class). 💡 **2026**: **standalone by default** (no `NgModule`), **OnPush** recommended, `input()`/`output()` signal functions.',
    },
  },
  {
    id: '2.2',
    theme: 'angular-core',
    fine: 'Components & Architecture',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Smart vs Dumb components ?',
      en: 'Smart vs Dumb components?',
    },
    a: {
      fr: '**Smart (container)** : logique métier, injecte des services, fait les appels, passe les données. **Dumb (présentationnel)** : affiche les `input()` reçus, émet via `output()`, pas de service, **OnPush**, hautement réutilisable.',
      en: '**Smart (container)**: business logic, injects services, makes calls, passes data down. **Dumb (presentational)**: renders received `input()`, emits via `output()`, no services, **OnPush**, highly reusable.',
    },
  },
  {
    id: '2.3',
    theme: 'angular-core',
    fine: 'Components & Architecture',
    diff: 2,
    modern: true,
    seed: false,
    q: {
      fr: 'Y a-t-il une relation entre les components ?',
      en: 'Is there a relationship between components?',
    },
    a: {
      fr: "Oui : **parent→enfant** via `input()`, **enfant→parent** via `output()`, **siblings** via un service partagé. 💡 **2026** : pour l'état partagé, un service **à base de signals** plutôt qu'un `BehaviorSubject`.",
      en: 'Yes: **parent→child** via `input()`, **child→parent** via `output()`, **siblings** via a shared service. 💡 **2026**: for shared state, a **signal-based** service rather than a `BehaviorSubject`.',
    },
  },
  {
    id: '2.4',
    theme: 'angular-core',
    fine: 'Components & Architecture',
    diff: 3,
    modern: false,
    seed: false,
    q: {
      fr: 'Tu montes une app Angular : quels pré-requis tu mets en place ?',
      en: 'Setting up an Angular app — what do you put in place?',
    },
    a: {
      fr: '**Archi en couches** (presentation/application/domain/infrastructure) + standalone + lazy loading ; **tooling** ESLint + Prettier + Husky + conventional commits ; **état** signals (NgRx si complexe) ; **tests** unitaires + E2E + coverage cible ; **CI/CD** pipeline build/test/deploy ; **doc** README + Compodoc/Storybook.',
      en: '**Layered architecture** (presentation/application/domain/infrastructure) + standalone + lazy loading; **tooling** ESLint + Prettier + Husky + conventional commits; **state** signals (NgRx if complex); **testing** unit + E2E + coverage target; **CI/CD** build/test/deploy pipeline; **docs** README + Compodoc/Storybook.',
    },
  },
  {
    id: '2.5',
    theme: 'angular-core',
    fine: 'Components & Architecture',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Structure de fichiers : tu pars où et pourquoi ?',
      en: 'File structure — where do you start and why?',
    },
    a: {
      fr: '**Feature-based** : `core/` (singletons, guards, interceptors), `shared/` (composants/pipes réutilisables), `features/<contexte>/{domain,application,infrastructure,presentation}`, `layout/`. Pourquoi : scalable, maintenable, lazy-loadable, on trouve vite le code.',
      en: '**Feature-based**: `core/` (singletons, guards, interceptors), `shared/` (reusable components/pipes), `features/<context>/{domain,application,infrastructure,presentation}`, `layout/`. Why: scalable, maintainable, lazy-loadable, easy to navigate.',
    },
  },
  {
    id: '2.6',
    theme: 'angular-core',
    fine: 'Components & Architecture',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Tu connais des architectures de fichiers ?',
      en: 'Which file architectures do you know?',
    },
    a: {
      fr: '**Feature-based** (recommandé), **Layer-based** (par type technique, moins scalable), **Atomic Design** (atoms→pages), **DDD** (par domaine, bounded contexts).',
      en: '**Feature-based** (recommended), **Layer-based** (by technical type, less scalable), **Atomic Design** (atoms→pages), **DDD** (by domain, bounded contexts).',
    },
  },
  {
    id: '2.7',
    theme: 'angular-core',
    fine: 'Components & Architecture',
    diff: 2,
    modern: true,
    seed: true,
    q: {
      fr: "NgModules vs standalone components : tu défends quoi aujourd'hui ?",
      en: 'NgModules vs standalone — what do you defend today?',
    },
    a: {
      fr: '**Standalone**, sans hésiter, depuis Angular 15+ (défaut depuis 17). Moins de boilerplate, imports explicites par composant, lazy loading par `loadComponent`, meilleur tree-shaking. Les `NgModule` ne restent que pour du legacy à migrer.',
      en: '**Standalone**, no hesitation, since Angular 15+ (default since 17). Less boilerplate, explicit per-component imports, `loadComponent` lazy loading, better tree-shaking. `NgModule` only survives in legacy code to migrate.',
    },
  },
  {
    id: '2.8',
    theme: 'angular-core',
    fine: 'Components & Architecture',
    diff: 3,
    modern: true,
    seed: true,
    q: {
      fr: "Zoneless Angular : qu'est-ce que ça change concrètement ?",
      en: 'Zoneless Angular — what changes in practice?',
    },
    a: {
      fr: "Plus de `zone.js` qui patche les API async → la change detection n'est plus déclenchée « automatiquement partout ». On rend l'état **explicitement réactif** via **signals** (un `set`/`update` notifie le framework). Bénéfices : bundles plus légers, CD plus prévisible et performante. 💡 **2026** : zoneless **stable** en Angular 22 (`provideZonelessChangeDetection()`).",
      en: 'No more `zone.js` patching async APIs → change detection isn\'t triggered "magically everywhere". State becomes **explicitly reactive** via **signals** (a `set`/`update` notifies the framework). Benefits: lighter bundles, more predictable & performant CD. 💡 **2026**: zoneless is **stable** in Angular 22 (`provideZonelessChangeDetection()`).',
    },
  },
  {
    id: '3.1',
    theme: 'angular-core',
    fine: 'Services & DI',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: 'Définis un service.',
      en: 'Define a service.',
    },
    a: {
      fr: 'Une **classe TS** `@Injectable` qui porte la logique métier réutilisable, la communication backend (HTTP) et le partage de données entre composants, fournie via la DI.',
      en: 'An `@Injectable` **TS class** holding reusable business logic, backend communication (HTTP) and data sharing between components, provided via DI.',
    },
  },
  {
    id: '3.2',
    theme: 'angular-core',
    fine: 'Services & DI',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "`providedIn: 'root'` : ça signifie quoi ?",
      en: "What does `providedIn: 'root'` mean?",
    },
    a: {
      fr: "Une **seule instance (singleton)** pour toute l'app, disponible partout sans import, et **tree-shakeable**. Alternatives : `'any'`, providers au niveau d'une route, ou `providers: []` au niveau d'un composant pour une instance locale.",
      en: "A **single (singleton)** instance app-wide, available everywhere without imports, and **tree-shakeable**. Alternatives: `'any'`, route-level providers, or component-level `providers: []` for a local instance.",
    },
  },
  {
    id: '3.3',
    theme: 'angular-core',
    fine: 'Services & DI',
    diff: 2,
    modern: true,
    seed: false,
    q: {
      fr: "Qu'est-ce que l'injection de dépendances (DI) ?",
      en: 'What is Dependency Injection (DI)?',
    },
    a: {
      fr: "Un **pattern** : on **fournit** les dépendances depuis l'extérieur au lieu de les créer dans la classe. Gains : testabilité (mocks faciles), découplage, réutilisabilité, maintenabilité. 💡 **2026** : `inject()` en fonction est souvent préféré à l'injection par constructeur.",
      en: 'A **pattern**: dependencies are **provided** from outside instead of created inside the class. Wins: testability (easy mocks), decoupling, reuse, maintainability. 💡 **2026**: the `inject()` function is often preferred over constructor injection.',
    },
  },
  {
    id: '3.4',
    theme: 'angular-core',
    fine: 'Services & DI',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'un Singleton ?",
      en: 'What is a Singleton?',
    },
    a: {
      fr: "Un pattern garantissant **une seule instance** d'une classe dans l'app. En Angular, `providedIn: 'root'` en crée un automatiquement. Use cases : `AuthService`, `ConfigService`, cache global.",
      en: "A pattern guaranteeing **one instance** of a class app-wide. In Angular, `providedIn: 'root'` creates one automatically. Use cases: `AuthService`, `ConfigService`, global cache.",
    },
  },
  {
    id: '4.1',
    theme: 'angular-core',
    fine: 'Templates & Binding',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: 'Les types de binding `()`, `[]`, `[()]` — y en a-t-il un autre ?',
      en: 'Binding types `()`, `[]`, `[()]` — any others?',
    },
    a: {
      fr: 'Interpolation `{{ }}`, property `[prop]`, event `(event)`, two-way `[(ngModel)]` ; plus attribute `[attr.x]`, class `[class.active]`, style `[style.color]`.',
      en: 'Interpolation `{{ }}`, property `[prop]`, event `(event)`, two-way `[(ngModel)]`; plus attribute `[attr.x]`, class `[class.active]`, style `[style.color]`.',
    },
  },
  {
    id: '4.2',
    theme: 'angular-core',
    fine: 'Templates & Binding',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: '`disabled` mal codé en HTML : le piège ?',
      en: 'The `disabled` HTML pitfall?',
    },
    a: {
      fr: 'En HTML natif, `disabled` est actif dès qu\'il est **présent**, même `disabled="false"`. Il faut le **property binding** : `[disabled]="isDisabled"`.',
      en: 'In native HTML, `disabled` is active as soon as it\'s **present**, even `disabled="false"`. Use **property binding**: `[disabled]="isDisabled"`.',
    },
  },
  {
    id: '4.3',
    theme: 'angular-core',
    fine: 'Templates & Binding',
    diff: 2,
    modern: true,
    seed: false,
    q: {
      fr: 'Les directives structurelles (`ngIf`, `ngFor`…) ?',
      en: 'Structural directives (`ngIf`, `ngFor`…)?',
    },
    a: {
      fr: 'Classiques : `*ngIf` (+ `else`/`then`), `*ngFor` (`index`, `first`, `last`, **`trackBy`** crucial perf), `[ngSwitch]`/`*ngSwitchCase`. 💡 **2026** : on utilise le **control flow natif `@if` / `@for` / `@switch`** (Angular 17+, recommandé/par défaut) — `@for` exige un **`track`**.',
      en: 'Classic: `*ngIf` (+ `else`/`then`), `*ngFor` (`index`, `first`, `last`, **`trackBy`** perf-critical), `[ngSwitch]`/`*ngSwitchCase`. 💡 **2026**: use the **native control flow `@if` / `@for` / `@switch`** (Angular 17+, default) — `@for` requires a **`track`**.',
    },
  },
  {
    id: '4.4',
    theme: 'angular-core',
    fine: 'Templates & Binding',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "`ngClass` : comment tu l'utilises ?",
      en: 'How do you use `ngClass`?',
    },
    a: {
      fr: '3 syntaxes : objet `[ngClass]="{active: isActive}"` (le plus courant), tableau `[\'btn\', role]`, ou méthode `getClasses()`. Pour une seule classe, `[class.active]="…"` est plus direct.',
      en: '3 syntaxes: object `[ngClass]="{active: isActive}"` (most common), array `[\'btn\', role]`, or method `getClasses()`. For a single class, `[class.active]="…"` is more direct.',
    },
  },
  {
    id: '4.5',
    theme: 'angular-core',
    fine: 'Templates & Binding',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'une directive ?",
      en: 'What is a directive?',
    },
    a: {
      fr: "Une **classe TS** qui modifie le comportement/apparence d'un élément. 3 types : **component** (directive avec template), **structurelle** (`@if`/`*ngFor`), **attribut** (`ngClass`, custom via `@HostListener`/`@HostBinding`).",
      en: "A **TS class** that alters an element's behavior/appearance. 3 types: **component** (directive with template), **structural** (`@if`/`*ngFor`), **attribute** (`ngClass`, custom via `@HostListener`/`@HostBinding`).",
    },
  },
  {
    id: '5.1',
    theme: 'angular-core',
    fine: 'Pipes',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Parle-nous des Pipes : natifs ? créer un custom ?',
      en: 'Tell us about Pipes: built-ins? creating a custom one?',
    },
    a: {
      fr: 'Fonction de transformation dans le template. Natifs : `uppercase`, `number`, `currency`, `percent`, `date`, `json`, et **`async`** (subscribe/unsubscribe auto — clé). Custom : `@Pipe({name, standalone: true})` + `transform()`. **Pure** (défaut, recalcul si la référence change) vs **impure** (chaque CD, ⚠️ perf).',
      en: 'A template transformation function. Built-ins: `uppercase`, `number`, `currency`, `percent`, `date`, `json`, and **`async`** (auto subscribe/unsubscribe — key). Custom: `@Pipe({name, standalone: true})` + `transform()`. **Pure** (default, recompute on reference change) vs **impure** (every CD, ⚠️ perf).',
    },
  },
  {
    id: '6.1',
    theme: 'angular-core',
    fine: 'Routing',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: 'Comment marchent les routes dans Angular ?',
      en: 'How does routing work in Angular?',
    },
    a: {
      fr: 'On déclare un tableau `Routes` (path→component), Angular utilise `<router-outlet>` comme emplacement, et remplace le contenu à la navigation **sans recharger** la page (SPA). Wildcard `**` pour le 404.',
      en: 'You declare a `Routes` array (path→component), Angular uses `<router-outlet>` as a placeholder and swaps content on navigation **without a full reload** (SPA). Wildcard `**` for 404.',
    },
  },
  {
    id: '6.2',
    theme: 'angular-core',
    fine: 'Routing',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce que `router-outlet` ?",
      en: 'What is `router-outlet`?',
    },
    a: {
      fr: "Une directive **placeholder** où Angular affiche le composant de la route active (comme un cadre photo dont l'image change selon l'URL).",
      en: "A **placeholder** directive where Angular renders the active route's component (like a photo frame whose image changes with the URL).",
    },
  },
  {
    id: '6.3',
    theme: 'angular-core',
    fine: 'Routing',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Lazy loading : comment améliorer la perf des routes ?',
      en: 'Lazy loading — how does it improve route performance?',
    },
    a: {
      fr: 'Charger un composant/feature **à la demande** via `loadComponent` / `loadChildren` → bundle initial plus petit, démarrage plus rapide, bande passante économisée.',
      en: 'Load a component/feature **on demand** via `loadComponent` / `loadChildren` → smaller initial bundle, faster startup, bandwidth saved.',
    },
  },
  {
    id: '7.1',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'un Observable ?",
      en: 'What is an Observable?',
    },
    a: {
      fr: "Un **flux asynchrone** qui émet 0..N valeurs dans le temps : **push-based**, **lazy** (s'exécute au `subscribe`), peut compléter ou émettre une erreur (`next`/`error`/`complete`).",
      en: 'An **async stream** emitting 0..N values over time: **push-based**, **lazy** (runs on `subscribe`), can complete or error (`next`/`error`/`complete`).',
    },
  },
  {
    id: '7.2',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'un Subject ?",
      en: 'What is a Subject?',
    },
    a: {
      fr: 'Un Observable spécial **multicast** et **hot** (émet sans subscriber), à la fois Observable et Observer. Variantes : `Subject`, `BehaviorSubject` (valeur initiale + dernière valeur), `ReplaySubject` (N dernières), `AsyncSubject` (dernière à la complétion).',
      en: 'A special **multicast**, **hot** Observable (emits without subscribers), both Observable and Observer. Variants: `Subject`, `BehaviorSubject` (initial + last value), `ReplaySubject` (last N), `AsyncSubject` (last on complete).',
    },
  },
  {
    id: '7.3',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Les Observables en Angular, concrètement ?',
      en: 'Observables in Angular, concretely?',
    },
    a: {
      fr: 'Partout : `HttpClient` (appels), `valueChanges` des forms (avec `debounceTime`/`switchMap`), `paramMap` du router, et état via service. À consommer de préférence avec le pipe `async`.',
      en: 'Everywhere: `HttpClient` (calls), form `valueChanges` (with `debounceTime`/`switchMap`), router `paramMap`, and service state. Best consumed with the `async` pipe.',
    },
  },
  {
    id: '7.4',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 3,
    modern: true,
    seed: true,
    q: {
      fr: "`signal()` vs `BehaviorSubject` pour de l'état local — comment tu choisis ?",
      en: '`signal()` vs `BehaviorSubject` for local state — how do you choose?',
    },
    a: {
      fr: "💡 **2026, défaut = signal** pour l'état synchrone d'UI : API simple (`set`/`update`/`computed`), pas de subscribe/unsubscribe, intégré à la CD zoneless, lecture directe `value()`. Je garde **RxJS** pour le **vrai asynchrone événementiel** (flux HTTP, debounce, websockets, orchestration d'événements). Interop via `toSignal()` / `toObservable()`.",
      en: '💡 **2026, default = signal** for synchronous UI state: simple API (`set`/`update`/`computed`), no subscribe/unsubscribe, integrated with zoneless CD, direct `value()` read. I keep **RxJS** for **genuinely async/event streams** (HTTP, debounce, websockets, event orchestration). Interop via `toSignal()` / `toObservable()`.',
    },
  },
  {
    id: '7.5',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 2,
    modern: true,
    seed: false,
    q: {
      fr: "Comment gérer l'état via un service ?",
      en: 'How do you manage state via a service?',
    },
    a: {
      fr: "💡 **2026** : service `@Injectable({providedIn:'root'})` exposant des **signals** privés + `computed` dérivés + méthodes de mutation (`set`/`update` immuables). Approche **legacy** : `BehaviorSubject` privé + `xxx$ = subject.asObservable()` + `.next([...current, item])`.",
      en: '💡 **2026**: a root `@Injectable` service exposing private **signals** + derived `computed` + mutation methods (immutable `set`/`update`). **Legacy** approach: private `BehaviorSubject` + `xxx$ = subject.asObservable()` + `.next([...current, item])`.',
    },
  },
  {
    id: '7.6',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Cite des opérateurs RxJS que tu connais.',
      en: 'Name some RxJS operators you know.',
    },
    a: {
      fr: 'Création `of/from/interval/timer/fromEvent` ; transfo `map/switchMap/mergeMap/concatMap` ; filtrage `filter/take/takeUntil/debounceTime/distinctUntilChanged` ; combinaison `combineLatest/forkJoin/merge` ; utilitaires `tap/catchError/retry`.',
      en: 'Creation `of/from/interval/timer/fromEvent`; transform `map/switchMap/mergeMap/concatMap`; filtering `filter/take/takeUntil/debounceTime/distinctUntilChanged`; combination `combineLatest/forkJoin/merge`; utility `tap/catchError/retry`.',
    },
  },
  {
    id: '7.7',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 3,
    modern: false,
    seed: true,
    q: {
      fr: '`switchMap` vs `mergeMap` vs `concatMap` vs `exhaustMap` — un cas réel chacun.',
      en: '`switchMap` vs `mergeMap` vs `concatMap` vs `exhaustMap` — a real case for each.',
    },
    a: {
      fr: "**switchMap** : autocomplete (annule la recherche précédente). **mergeMap** : envoyer N requêtes en parallèle indépendantes (upload de fichiers). **concatMap** : préserver l'ordre (file d'actions séquentielles). **exhaustMap** : ignorer les déclenchements pendant un traitement en cours (anti-double-clic sur un bouton login).",
      en: '**switchMap**: autocomplete (cancel the previous search). **mergeMap**: fire N independent parallel requests (file uploads). **concatMap**: preserve order (sequential action queue). **exhaustMap**: ignore triggers while one is in-flight (anti-double-click on a login button).',
    },
  },
  {
    id: '7.8',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 2,
    modern: true,
    seed: false,
    q: {
      fr: 'Comment gérer/automatiser la désinscription ?',
      en: 'How do you handle/automate unsubscription?',
    },
    a: {
      fr: '💡 **2026, priorité** : pipe **`async`** dans le template, et **`takeUntilDestroyed()`** dans la classe. Legacy : `takeUntil(destroy$)` + `ngOnDestroy`, ou `Subscription` manuelle. Souvent, passer aux **signals** supprime carrément le problème.',
      en: '💡 **2026, prefer**: the **`async`** pipe in templates and **`takeUntilDestroyed()`** in classes. Legacy: `takeUntil(destroy$)` + `ngOnDestroy`, or manual `Subscription`. Often, moving to **signals** removes the problem entirely.',
    },
  },
  {
    id: '7.9',
    theme: 'rxjs-signals',
    fine: 'RxJS & Signals',
    diff: 3,
    modern: false,
    seed: true,
    q: {
      fr: 'Interop Signals ↔ RxJS (`toSignal`/`toObservable`) : un piège rencontré ?',
      en: 'Signals ↔ RxJS interop — a pitfall you hit?',
    },
    a: {
      fr: "`toSignal()` **subscribe immédiatement** et a besoin d'une valeur initiale (sinon `undefined` au premier rendu) → bien typer/`initialValue`. Et `toObservable()` émet sur la base de l'effet : attention aux **émissions en doublon** ou au timing si on attendait une sémantique « valeur courante » stricte.",
      en: '`toSignal()` **subscribes immediately** and needs an initial value (else `undefined` on first render) → set `initialValue`/type carefully. And `toObservable()` emits based on an effect: watch for **duplicate emissions** or timing if you expected strict "current value" semantics.',
    },
  },
  {
    id: '8.1',
    theme: 'architecture',
    fine: 'State Management',
    diff: 2,
    modern: true,
    seed: false,
    q: {
      fr: 'As-tu déjà mis en place un store ?',
      en: 'Have you ever set up a store?',
    },
    a: {
      fr: 'Oui. 💡 **2026** : **signals + `computed`** dans un service pour petit/moyen état (souvent suffisant). **NgRx** (Redux : actions/reducers/selectors/effects, DevTools, verbeux mais scalable) pour grosse app avec mutations complexes. Akita = intermédiaire.',
      en: 'Yes. 💡 **2026**: **signals + `computed`** in a service for small/medium state (often enough). **NgRx** (Redux: actions/reducers/selectors/effects, DevTools, verbose but scalable) for large apps with complex mutations. Akita = middle ground.',
    },
  },
  {
    id: '8.2',
    theme: 'architecture',
    fine: 'State Management',
    diff: 3,
    modern: true,
    seed: true,
    q: {
      fr: "Stratégie d'état pour une grosse app : Signals seuls, NgRx, autre — sur quels critères ?",
      en: 'State strategy for a big app: signals only, NgRx, other — on what criteria?',
    },
    a: {
      fr: "Critères : **partage** (combien de features touchent l'état), **complexité des mutations**, besoin de **traçabilité/time-travel**, taille d'équipe. Petit/moyen → signals services. Beaucoup d'effets de bord async + audit → NgRx (ou **NgRx SignalStore** qui marie signals + structure). Ne pas sur-architecturer une petite app.",
      en: "Criteria: **sharing** (how many features touch the state), **mutation complexity**, need for **traceability/time-travel**, team size. Small/medium → signal services. Heavy async side-effects + audit → NgRx (or **NgRx SignalStore**, which marries signals + structure). Don't over-architect a small app.",
    },
  },
  {
    id: '9.1',
    theme: 'architecture',
    fine: 'HTTP & APIs',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: 'Décris un appel HTTP REST.',
      en: 'Describe a REST HTTP call.',
    },
    a: {
      fr: 'Une requête = **method** (GET/POST/PUT/PATCH/DELETE) + **URL/endpoint** + **headers** (Content-Type, Authorization) + **body** (POST/PUT/PATCH). Réponse = **status** (2xx succès, 4xx erreur client, 5xx erreur serveur) + body.',
      en: 'A request = **method** (GET/POST/PUT/PATCH/DELETE) + **URL/endpoint** + **headers** (Content-Type, Authorization) + **body** (POST/PUT/PATCH). Response = **status** (2xx success, 4xx client error, 5xx server error) + body.',
    },
  },
  {
    id: '9.2',
    theme: 'architecture',
    fine: 'HTTP & APIs',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce qu'une API REST ?",
      en: 'What is a REST API?',
    },
    a: {
      fr: "Une API dont l'architecture s'appuie sur **HTTP** : ressources adressées par URL, opérations via les méthodes HTTP, sans état (stateless).",
      en: 'An API whose architecture relies on **HTTP**: resources addressed by URL, operations via HTTP methods, stateless.',
    },
  },
  {
    id: '9.3',
    theme: 'architecture',
    fine: 'HTTP & APIs',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce que CRUD ?",
      en: 'What is CRUD?',
    },
    a: {
      fr: '**Create / Read / Update / Delete** ↔ POST / GET / PUT (ou PATCH partiel) / DELETE.',
      en: '**Create / Read / Update / Delete** ↔ POST / GET / PUT (or PATCH for partial) / DELETE.',
    },
  },
  {
    id: '11.1',
    theme: 'architecture',
    fine: 'Design Patterns',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce que le Clean Code ?",
      en: 'What is Clean Code?',
    },
    a: {
      fr: "Du code **lisible et maintenable** : nommage explicite, fonctions courtes (1 responsabilité), **DRY**, commentaires seulement si nécessaire (le code s'auto-explique), principes **SOLID**.",
      en: '**Readable, maintainable** code: explicit naming, short single-responsibility functions, **DRY**, comments only when needed (code self-explains), **SOLID** principles.',
    },
  },
  {
    id: '11.2',
    theme: 'architecture',
    fine: 'Design Patterns',
    diff: 3,
    modern: false,
    seed: false,
    q: {
      fr: 'Clean Architecture / Hexagonale ?',
      en: 'Clean / Hexagonal Architecture?',
    },
    a: {
      fr: '**Ports & Adapters** : isoler la logique métier des détails techniques. Le **domaine** (pur) ne dépend de rien ; les **ports** (interfaces) sont implémentés par des **adapters** (HTTP, DB). Avantages : domaine testable sans dépendances, implémentations interchangeables.',
      en: '**Ports & Adapters**: isolate business logic from technical details. The **domain** (pure) depends on nothing; **ports** (interfaces) are implemented by **adapters** (HTTP, DB). Benefits: domain testable without deps, swappable implementations.',
    },
  },
  {
    id: '11.3',
    theme: 'architecture',
    fine: 'Design Patterns',
    diff: 3,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce que le DDD ?",
      en: 'What is DDD?',
    },
    a: {
      fr: "Approche **centrée métier** : Ubiquitous Language (vocabulaire commun devs/métier), Bounded Contexts, Entities (identité), Value Objects (comparés par valeur), Aggregates, Repository pattern (abstraction de l'accès données).",
      en: 'A **domain-centric** approach: Ubiquitous Language (shared dev/business vocabulary), Bounded Contexts, Entities (identity), Value Objects (compared by value), Aggregates, Repository pattern (data-access abstraction).',
    },
  },
  {
    id: '14.1',
    theme: 'architecture',
    fine: 'Micro-Frontends',
    diff: 3,
    modern: false,
    seed: false,
    q: {
      fr: 'Web Components et micro-frontends ?',
      en: 'Web Components and micro-frontends?',
    },
    a: {
      fr: '**Web Components** : standards (Custom Elements, Shadow DOM, Templates) pour des composants réutilisables indépendants du framework. **Micro-frontends** : app découpée en features développées/déployées séparément. Avantages : équipes autonomes, déploiement indépendant ; inconvénients : complexité, duplication, perf (multi-bundles). Approches : iframe, Web Components, Module Federation, Single-SPA.',
      en: '**Web Components**: standards (Custom Elements, Shadow DOM, Templates) for framework-agnostic reusable components. **Micro-frontends**: app split into separately built/deployed features. Pros: autonomous teams, independent deploy; cons: complexity, duplication, perf (multi-bundles). Approaches: iframe, Web Components, Module Federation, Single-SPA.',
    },
  },
  {
    id: '14.2',
    theme: 'architecture',
    fine: 'Micro-Frontends',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Custom element ? Angular element ?',
      en: 'Custom element? Angular element?',
    },
    a: {
      fr: '**Custom Element** : standard web pour des balises HTML personnalisées. **Angular Elements** (`@angular/elements`, `createCustomElement`) convertit un composant Angular en Web Component utilisable partout (React, Vue, vanilla).',
      en: '**Custom Element**: web standard for custom HTML tags. **Angular Elements** (`@angular/elements`, `createCustomElement`) turns an Angular component into a Web Component usable anywhere (React, Vue, vanilla).',
    },
  },
  {
    id: '14.3',
    theme: 'architecture',
    fine: 'Micro-Frontends',
    diff: 3,
    modern: false,
    seed: false,
    q: {
      fr: 'Partager des composants entre Angular et React ?',
      en: 'Sharing components between Angular and React?',
    },
    a: {
      fr: '3 voies : **Angular Elements** (petits composants), **Stencil** (design system framework-agnostic), ou **logique headless** partagée (lib TS pure) + UI propre à chaque framework, en mutualisant les styles (CSS/tokens).',
      en: '3 paths: **Angular Elements** (small components), **Stencil** (framework-agnostic design system), or shared **headless logic** (pure TS lib) + per-framework UI, sharing styles (CSS/tokens).',
    },
  },
  {
    id: '12.1',
    theme: 'performance',
    fine: 'Change Detection',
    diff: 3,
    modern: true,
    seed: true,
    q: {
      fr: "La change detection, tu peux m'en parler ? (et OnPush)",
      en: 'Tell me about change detection (and OnPush).',
    },
    a: {
      fr: "Mécanisme par lequel Angular détecte les changements d'état et met à jour le DOM. **Default** : vérifie tout l'arbre à chaque événement (simple, peut être lent). **OnPush** : ne vérifie que si un `input()` change (nouvelle réf), un événement interne survient, un Observable émet (async), ou `markForCheck()`. 💡 **2026** : en **zoneless**, les **signals** déclenchent la CD de façon granulaire — bascule à OnPush + signals par défaut.",
      en: 'The mechanism by which Angular detects state changes and updates the DOM. **Default**: checks the whole tree on each event (simple, can be slow). **OnPush**: checks only when an `input()` changes (new ref), an internal event fires, an Observable emits (async), or `markForCheck()`. 💡 **2026**: in **zoneless**, **signals** trigger CD granularly — go OnPush + signals by default.',
    },
  },
  {
    id: '12.2',
    theme: 'performance',
    fine: 'Rendering',
    diff: 3,
    modern: false,
    seed: true,
    q: {
      fr: 'Diagnostiquer/corriger un rendu lent sur une grosse liste ?',
      en: 'Diagnose/fix slow rendering on a big list?',
    },
    a: {
      fr: 'Mesurer (Angular DevTools profiler), puis : **`track`** sur `@for` (évite de re-render tout), **OnPush**, **virtual scroll** (`cdk-virtual-scroll-viewport`), pagination/lazy, éviter les pipes impurs et le travail lourd dans le template, `computed` mémoïsé.',
      en: 'Measure (Angular DevTools profiler), then: **`track`** on `@for` (avoid full re-render), **OnPush**, **virtual scroll** (`cdk-virtual-scroll-viewport`), pagination/lazy, avoid impure pipes and heavy template work, memoized `computed`.',
    },
  },
  {
    id: '12.3',
    theme: 'performance',
    fine: 'Rendering',
    diff: 2,
    modern: false,
    seed: true,
    q: {
      fr: '`trackBy` / `@for` track : pourquoi critique ?',
      en: '`trackBy` / `@for` track — why critical?',
    },
    a: {
      fr: "Sans clé de tracking, Angular **détruit/recrée** tous les nœuds DOM quand la liste change → coûteux et perte d'état (focus, animations). Avec `track item.id`, il **réconcilie** uniquement ce qui a changé.",
      en: 'Without a tracking key, Angular **destroys/recreates** all DOM nodes when the list changes → costly and loses state (focus, animations). With `track item.id`, it **reconciles** only what changed.',
    },
  },
  {
    id: '12.4',
    theme: 'performance',
    fine: 'SSR & Web Vitals',
    diff: 3,
    modern: true,
    seed: true,
    q: {
      fr: "Améliorer le LCP d'une app Angular SSR ?",
      en: 'Improve LCP of an Angular SSR app?',
    },
    a: {
      fr: '**SSR + hydration** (incrémentale/`@defer`), `NgOptimizedImage` pour le LCP image, **lazy loading** des routes, réduire le JS initial (standalone + tree-shaking esbuild), `preconnect`/`preload` des ressources critiques, éviter le CLS (dimensions réservées).',
      en: '**SSR + hydration** (incremental/`@defer`), `NgOptimizedImage` for the LCP image, route **lazy loading**, reduce initial JS (standalone + esbuild tree-shaking), `preconnect`/`preload` critical resources, avoid CLS (reserved dimensions).',
    },
  },
  {
    id: '12.5',
    theme: 'performance',
    fine: 'Observabilité',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "Quels outils d'observabilité ?",
      en: 'Which observability tools?',
    },
    a: {
      fr: '**APM/erreurs** : Sentry, New Relic, Datadog. **Logging** : ELK, Splunk, CloudWatch. **RUM/session** : GA, Hotjar, LogRocket. **Perf** : Lighthouse, WebPageTest, Bundle/Source-Map Analyzer. **Angular** : Angular DevTools.',
      en: '**APM/errors**: Sentry, New Relic, Datadog. **Logging**: ELK, Splunk, CloudWatch. **RUM/session**: GA, Hotjar, LogRocket. **Perf**: Lighthouse, WebPageTest, Bundle/Source-Map Analyzer. **Angular**: Angular DevTools.',
    },
  },
  {
    id: '10.1',
    theme: 'testing',
    fine: 'Testing',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "Qu'est-ce que le TDD et comment le mettre en place ?",
      en: 'What is TDD and how do you apply it?',
    },
    a: {
      fr: 'Écrire les **tests avant** le code. Cycle **Red→Green→Refactor** : test qui échoue, code minimal pour passer, nettoyage. En place : framework de test, suivre le cycle, coverage cible, intégration CI.',
      en: 'Write **tests before** code. **Red→Green→Refactor** cycle: failing test, minimal code to pass, cleanup. Setup: test framework, follow the cycle, coverage target, CI integration.',
    },
  },
  {
    id: '10.2',
    theme: 'testing',
    fine: 'Testing',
    diff: 2,
    modern: true,
    seed: false,
    q: {
      fr: "De quels tests as-tu l'habitude ?",
      en: 'What testing do you usually set up?',
    },
    a: {
      fr: '**Unitaires** (services, pipes, fonctions pures), **intégration** (composant + dépendances), **E2E** (parcours critiques, formulaires, nav). 💡 **2026** : runner **Vitest** par défaut côté Angular ; pattern **AAA** (Arrange-Act-Assert).',
      en: '**Unit** (services, pipes, pure functions), **integration** (component + deps), **E2E** (critical flows, forms, nav). 💡 **2026**: **Vitest** as default Angular runner; **AAA** pattern (Arrange-Act-Assert).',
    },
  },
  {
    id: '10.3',
    theme: 'testing',
    fine: 'Testing',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Différence tests unitaires vs E2E ?',
      en: 'Difference between unit and E2E tests?',
    },
    a: {
      fr: "**Unitaires** : unité isolée, rapides (ms), nombreux, dépendances mockées. **E2E** : app complète côté utilisateur, lents (s/min), peu nombreux, vraies dépendances. Suivre la **pyramide des tests** (beaucoup d'unitaires, peu d'E2E).",
      en: "**Unit**: isolated unit, fast (ms), many, mocked deps. **E2E**: full app from the user's view, slow (s/min), few, real deps. Follow the **test pyramid** (many unit, few E2E).",
    },
  },
  {
    id: '10.4',
    theme: 'testing',
    fine: 'Testing',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Bonnes pratiques E2E ?',
      en: 'E2E best practices?',
    },
    a: {
      fr: '**Sélecteurs stables** (`data-cy`/`data-testid`, pas de CSS fragile), tests **indépendants**, setup/teardown des données, **attentes explicites** (pas de `wait` fixe), **Page Object Pattern**.',
      en: '**Stable selectors** (`data-cy`/`data-testid`, no fragile CSS), **independent** tests, data setup/teardown, **explicit waits** (no fixed `wait`), **Page Object Pattern**.',
    },
  },
  {
    id: '10.5',
    theme: 'testing',
    fine: 'Testing',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: 'Quel sélecteur en Cypress ?',
      en: 'Which selector in Cypress?',
    },
    a: {
      fr: 'Ordre : `data-cy`/`data-testid` (meilleur), puis `id` stable, classes sémantiques en dernier recours. À éviter : CSS complexe (`div > p:nth-child(2)`), classes de style (`.btn-primary`), texte (fragile en i18n).',
      en: 'Order: `data-cy`/`data-testid` (best), then stable `id`, semantic classes as a last resort. Avoid: complex CSS (`div > p:nth-child(2)`), style classes (`.btn-primary`), text (fragile with i18n).',
    },
  },
  {
    id: '10.6',
    theme: 'testing',
    fine: 'Testing',
    diff: 3,
    modern: false,
    seed: true,
    q: {
      fr: 'Ta stratégie de tests : que tester, que NE PAS tester ?',
      en: 'Your testing strategy: what to test, what NOT to test?',
    },
    a: {
      fr: '**Tester** : règles métier, mappers/transformations, stores/état, parcours critiques. **Ne pas tester** : le framework lui-même, les internals de libs tierces, le code généré, les getters triviaux. Viser la valeur, pas le % de coverage pour le %.',
      en: "**Test**: business rules, mappers/transformations, stores/state, critical flows. **Don't test**: the framework itself, third-party internals, generated code, trivial getters. Aim for value, not coverage % for its own sake.",
    },
  },
  {
    id: '10.7',
    theme: 'testing',
    fine: 'Testing',
    diff: 3,
    modern: true,
    seed: true,
    q: {
      fr: 'Comment organiser un setup de test avec Signals / composants standalone ?',
      en: 'How do you organize a test setup with signals / standalone components?',
    },
    a: {
      fr: "`TestBed` qui **importe** le composant standalone directement (plus de module de test). Pour les signals, on **set** l'état puis on **lit** le rendu/`computed` (pas de tick zone en zoneless : déclencher la CD explicitement). Mocker les services injectés via `providers`.",
      en: '`TestBed` that **imports** the standalone component directly (no test module). For signals, **set** state then **read** the render/`computed` (no zone tick in zoneless: trigger CD explicitly). Mock injected services via `providers`.',
    },
  },
  {
    id: '13.1',
    theme: 'testing',
    fine: 'Tooling & Build',
    diff: 2,
    modern: true,
    seed: false,
    q: {
      fr: 'Tu gères Webpack ? Comment en local ?',
      en: 'Do you handle Webpack? How locally?',
    },
    a: {
      fr: "L'**Angular CLI** gère le bundler sous le capot (config via `angular.json`, pas de `webpack.config.js`). En local : `ng serve` (HMR), `ng build`, `ng build --watch`. Customisation rare via `@angular-builders/custom-webpack`. 💡 **2026** : la CLI utilise **esbuild/Vite** par défaut (build bien plus rapide que Webpack).",
      en: 'The **Angular CLI** manages the bundler under the hood (config via `angular.json`, no `webpack.config.js`). Locally: `ng serve` (HMR), `ng build`, `ng build --watch`. Rare customization via `@angular-builders/custom-webpack`. 💡 **2026**: the CLI uses **esbuild/Vite** by default (much faster than Webpack).',
    },
  },
  {
    id: '13.2',
    theme: 'testing',
    fine: 'Tooling & Build',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: 'Que fait un bundler (Webpack/esbuild) ?',
      en: 'What does a bundler (Webpack/esbuild) do?',
    },
    a: {
      fr: '**Bundling**, **minification**, **tree-shaking** (supprime le code mort), **code splitting** (lazy), **HMR**, **source maps**.',
      en: '**Bundling**, **minification**, **tree-shaking** (removes dead code), **code splitting** (lazy), **HMR**, **source maps**.',
    },
  },
  {
    id: '16.1',
    theme: 'testing',
    fine: 'DevOps & CI/CD',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "C'est quoi les « balises » CI ?",
      en: 'What are CI "tags"?',
    },
    a: {
      fr: 'Des marqueurs qui déclenchent des actions dans la pipeline : **tags Git** (`v1.0.0` → build prod/release/deploy), **flags dans les messages de commit** (`[ci skip]`, `[deploy]`), **patterns de branches** (`main`, `release-*`), **environment tags** (staging/production). Pipeline type : commit → build → tests → lint → build prod → deploy.',
      en: 'Markers that trigger pipeline actions: **Git tags** (`v1.0.0` → prod build/release/deploy), **commit-message flags** (`[ci skip]`, `[deploy]`), **branch patterns** (`main`, `release-*`), **environment tags** (staging/production). Typical pipeline: commit → build → tests → lint → prod build → deploy.',
    },
  },
  {
    id: '15.1',
    theme: 'a11y',
    fine: 'Accessibilité',
    diff: 3,
    modern: false,
    seed: true,
    q: {
      fr: "Rendre un composant custom (ex : dropdown) accessible clavier + lecteur d'écran ?",
      en: 'Make a custom component (e.g. dropdown) keyboard + screen-reader accessible?',
    },
    a: {
      fr: 'HTML **sémantique** d\'abord (`button`, `ul/li`), rôles ARIA si besoin (`role="listbox"`/`option`, `aria-expanded`, `aria-activedescendant`), navigation **clavier** complète (flèches, Échap, Entrée, Tab), **focus visible** et **focus management** (Angular **CDK a11y** : `FocusTrap`, `LiveAnnouncer`, `cdkTrapFocus`), labels associés.',
      en: '**Semantic** HTML first (`button`, `ul/li`), ARIA roles if needed (`role="listbox"`/`option`, `aria-expanded`, `aria-activedescendant`), full **keyboard** nav (arrows, Esc, Enter, Tab), **visible focus** and **focus management** (Angular **CDK a11y**: `FocusTrap`, `LiveAnnouncer`, `cdkTrapFocus`), associated labels.',
    },
  },
  {
    id: '15.2',
    theme: 'a11y',
    fine: 'Accessibilité',
    diff: 2,
    modern: false,
    seed: true,
    q: {
      fr: 'ARIA : une erreur fréquente que tu vois ?',
      en: 'ARIA — a common mistake you see?',
    },
    a: {
      fr: "**Sur-utiliser ARIA** là où l'HTML natif suffit (`<div role=\"button\">` au lieu de `<button>`), ou poser des `aria-*` qui **mentent** sur l'état réel (ex `aria-hidden` sur un élément focusable). Règle d'or : *no ARIA is better than bad ARIA*.",
      en: '**Overusing ARIA** where native HTML suffices (`<div role="button">` instead of `<button>`), or `aria-*` that **lies** about real state (e.g. `aria-hidden` on a focusable element). Golden rule: *no ARIA is better than bad ARIA*.',
    },
  },
  {
    id: '17.1',
    theme: 'soft',
    fine: 'Soft skills & Lead',
    diff: 1,
    modern: false,
    seed: false,
    q: {
      fr: "Ratio back/front, qu'est-ce que tu préfères ?",
      en: 'Back/front ratio — what do you prefer?',
    },
    a: {
      fr: "Réponse honnête selon ton profil : expertise **frontend Angular** assumée (ex 80/20 ou 70/30 si à l'aise Node/NestJS), capacité d'adaptation, exemples concrets. Le message : « je livre de la valeur sur toute la chaîne, mon point fort est le front ».",
      en: 'Answer honestly per your profile: owned **frontend Angular** expertise (e.g. 80/20, or 70/30 if comfortable with Node/NestJS), adaptability, concrete examples. The message: "I deliver value across the chain; my strength is the front-end."',
    },
  },
  {
    id: '17.2',
    theme: 'soft',
    fine: 'Soft skills & Lead',
    diff: 2,
    modern: false,
    seed: true,
    q: {
      fr: 'Comment tu fais monter un junior en compétence sur Angular ?',
      en: 'How do you upskill a junior on Angular?',
    },
    a: {
      fr: "**Onboarding** (doc, pair programming, walkthrough), **formation continue** (code reviews avec feedback constructif, best practices, sessions ciblées RxJS/signals/routing), **autonomie progressive** (tâches de complexité croissante, droit à l'erreur), **accompagnement** (dispo, feedback régulier pas que négatif).",
      en: '**Onboarding** (docs, pair programming, walkthrough), **continuous learning** (code reviews with constructive feedback, best practices, targeted RxJS/signals/routing sessions), **progressive autonomy** (increasing task complexity, room to fail), **support** (availability, regular feedback, not only negative).',
    },
  },
  {
    id: '17.3',
    theme: 'soft',
    fine: 'Soft skills & Lead',
    diff: 2,
    modern: false,
    seed: false,
    q: {
      fr: "Comment tu as mesuré l'impact de ton encadrement ?",
      en: 'How did you measure the impact of your mentoring?',
    },
    a: {
      fr: "**Quantitatif** : PR mergées sans aide, temps de résolution en baisse, taux d'acceptance des PR, coverage maintenu. **Qualitatif** : autonomie (moins de questions), qualité du code, propositions d'amélioration d'archi. **Feedback** : retours juniors/équipe, 1-on-1. Ex : passage de 3-4 aller-retours par PR à 1 en 3 mois.",
      en: '**Quantitative**: PRs merged unaided, falling resolution time, PR acceptance rate, coverage held. **Qualitative**: autonomy (fewer questions), code quality, architecture proposals. **Feedback**: junior/team feedback, 1-on-1s. E.g. from 3-4 review round-trips per PR down to 1 in 3 months.',
    },
  },
  {
    id: '17.4',
    theme: 'soft',
    fine: 'Soft skills & Lead',
    diff: 2,
    modern: false,
    seed: true,
    q: {
      fr: "Un désaccord technique en équipe : comment tu l'as tranché ?",
      en: 'A technical disagreement in the team — how did you settle it?',
    },
    a: {
      fr: "Ramener au **critère objectif** (perf, maintenabilité, coût, risque), faire un **spike/POC** ou un ADR comparatif quand c'est possible, écouter le « pourquoi » de l'autre, décider en explicitant le **trade-off** assumé, et **se rallier** une fois la décision prise (disagree & commit). Exemple concret de ta carrière > théorie.",
      en: 'Bring it back to an **objective criterion** (perf, maintainability, cost, risk), run a **spike/POC** or a comparative ADR when possible, hear the other\'s "why", decide by making the **trade-off** explicit, and **commit** once decided (disagree & commit). A concrete example from your career beats theory.',
    },
  },
] as const;
